#!/usr/bin/python
# -*- coding: utf-8 -*-

import cgi
import base64
import wsgiref.handlers
from google.appengine.ext import webapp

class GetPinyin(webapp.RequestHandler):
	pydict = {'阿' : 'A','啊' : 'A','吖' : 'A','嗄' : 'A','腌' : 'A','锕' : 'A',
'埃' : 'Ai','挨' : 'Ai','哎' : 'Ai','唉' : 'Ai','哀' : 'Ai','皑' : 'Ai','癌' : 'Ai','蔼' : 'Ai','矮' : 'Ai','艾' : 'Ai','碍' : 'Ai','爱' : 'Ai','隘' : 'Ai','捱' : 'Ai','嗳' : 'Ai','嗌' : 'Ai','嫒' : 'Ai','瑷' : 'Ai','暧' : 'Ai','砹' : 'Ai','锿' : 'Ai','霭' : 'Ai',
'鞍' : 'An','氨' : 'An','安' : 'An','俺' : 'An','按' : 'An','暗' : 'An','岸' : 'An','胺' : 'An','案' : 'An','谙' : 'An','埯' : 'An','揞' : 'An','庵' : 'An','桉' : 'An','铵' : 'An','鹌' : 'An','黯' : 'An',
'肮' : 'Ang','昂' : 'Ang','盎' : 'Ang',
'凹' : 'Ao','敖' : 'Ao','熬' : 'Ao','翱' : 'Ao','袄' : 'Ao','傲' : 'Ao','奥' : 'Ao','懊' : 'Ao','澳' : 'Ao','坳' : 'Ao','嗷' : 'Ao','岙' : 'Ao','廒' : 'Ao','遨' : 'Ao','媪' : 'Ao','骜' : 'Ao','獒' : 'Ao','聱' : 'Ao','螯' : 'Ao','鏊' : 'Ao','鳌' : 'Ao','鏖' : 'Ao',
'芭' : 'Ba','捌' : 'Ba','扒' : 'Ba','叭' : 'Ba','吧' : 'Ba','笆' : 'Ba','八' : 'Ba','疤' : 'Ba','巴' : 'Ba','拔' : 'Ba','跋' : 'Ba','靶' : 'Ba','把' : 'Ba','耙' : 'Ba','坝' : 'Ba','霸' : 'Ba','罢' : 'Ba','爸' : 'Ba','茇' : 'Ba','菝' : 'Ba','岜' : 'Ba','灞' : 'Ba','钯' : 'Ba','粑' : 'Ba','鲅' : 'Ba','魃' : 'Ba',
'白' : 'Bai','柏' : 'Bai','百' : 'Bai','摆' : 'Bai','佰' : 'Bai','败' : 'Bai','拜' : 'Bai','稗' : 'Bai','捭' : 'Bai','掰' : 'Bai',
'斑' : 'Ban','班' : 'Ban','搬' : 'Ban','扳' : 'Ban','般' : 'Ban','颁' : 'Ban','板' : 'Ban','版' : 'Ban','扮' : 'Ban','拌' : 'Ban','伴' : 'Ban','瓣' : 'Ban','半' : 'Ban','办' : 'Ban','绊' : 'Ban','阪' : 'Ban','坂' : 'Ban','钣' : 'Ban','瘢' : 'Ban','癍' : 'Ban','舨' : 'Ban',
'邦' : 'Bang','帮' : 'Bang','梆' : 'Bang','榜' : 'Bang','膀' : 'Bang','绑' : 'Bang','棒' : 'Bang','磅' : 'Bang','镑' : 'Bang','傍' : 'Bang','谤' : 'Bang','蒡' : 'Bang','浜' : 'Bang',
'蚌' : 'Beng','崩' : 'Beng','绷' : 'Beng','甭' : 'Beng','泵' : 'Beng','蹦' : 'Beng','迸' : 'Beng','嘣' : 'Beng','甏' : 'Beng',
'苞' : 'Bao','胞' : 'Bao','包' : 'Bao','褒' : 'Bao','薄' : 'Bao','雹' : 'Bao','保' : 'Bao','堡' : 'Bao','饱' : 'Bao','宝' : 'Bao','抱' : 'Bao','报' : 'Bao','暴' : 'Bao','豹' : 'Bao','鲍' : 'Bao','爆' : 'Bao','曝' : 'Bao','勹' : 'Bao','葆' : 'Bao','孢' : 'Bao','煲' : 'Bao','鸨' : 'Bao','褓' : 'Bao','趵' : 'Bao','龅' : 'Bao',
'剥' : 'Bo','玻' : 'Bo','菠' : 'Bo','播' : 'Bo','拨' : 'Bo','钵' : 'Bo','波' : 'Bo','博' : 'Bo','勃' : 'Bo','搏' : 'Bo','铂' : 'Bo','箔' : 'Bo','伯' : 'Bo','帛' : 'Bo','舶' : 'Bo','脖' : 'Bo','膊' : 'Bo','渤' : 'Bo','泊' : 'Bo','驳' : 'Bo','亳' : 'Bo','啵' : 'Bo','饽' : 'Bo','檗' : 'Bo','擘' : 'Bo','礴' : 'Bo','钹' : 'Bo','鹁' : 'Bo','簸' : 'Bo','跛' : 'Bo','踣' : 'Bo',
'杯' : 'Bei','碑' : 'Bei','悲' : 'Bei','卑' : 'Bei','北' : 'Bei','辈' : 'Bei','背' : 'Bei','贝' : 'Bei','钡' : 'Bei','倍' : 'Bei','狈' : 'Bei','备' : 'Bei','惫' : 'Bei','焙' : 'Bei','被' : 'Bei','孛' : 'Bei','陂' : 'Bei','邶' : 'Bei','蓓' : 'Bei','呗' : 'Bei','悖' : 'Bei','碚' : 'Bei','鹎' : 'Bei','褙' : 'Bei','鐾' : 'Bei','鞴' : 'Bei',
'奔' : 'Ben','苯' : 'Ben','本' : 'Ben','笨' : 'Ben','畚' : 'Ben','坌' : 'Ben','锛' : 'Ben',
'逼' : 'Bi','鼻' : 'Bi','比' : 'Bi','鄙' : 'Bi','笔' : 'Bi','彼' : 'Bi','碧' : 'Bi','蓖' : 'Bi','蔽' : 'Bi','毕' : 'Bi','毙' : 'Bi','毖' : 'Bi','币' : 'Bi','庇' : 'Bi','痹' : 'Bi','闭' : 'Bi','敝' : 'Bi','弊' : 'Bi','必' : 'Bi','壁' : 'Bi','臂' : 'Bi','避' : 'Bi','陛' : 'Bi','匕' : 'Bi','俾' : 'Bi','荜' : 'Bi','荸' : 'Bi','萆' : 'Bi','薜' : 'Bi','吡' : 'Bi','哔' : 'Bi','狴' : 'Bi','庳' : 'Bi','愎' : 'Bi','滗' : 'Bi','濞' : 'Bi','弼' : 'Bi','妣' : 'Bi','婢' : 'Bi','嬖' : 'Bi','璧' : 'Bi','贲' : 'Bi','睥' : 'Bi','畀' : 'Bi','铋' : 'Bi','秕' : 'Bi','裨' : 'Bi','筚' : 'Bi','箅' : 'Bi','篦' : 'Bi','舭' : 'Bi','襞' : 'Bi','跸' : 'Bi','髀' : 'Bi',
'辟' : 'Pi','坯' : 'Pi','砒' : 'Pi','霹' : 'Pi','批' : 'Pi','披' : 'Pi','劈' : 'Pi','琵' : 'Pi','毗' : 'Pi','啤' : 'Pi','脾' : 'Pi','疲' : 'Pi','皮' : 'Pi','匹' : 'Pi','痞' : 'Pi','僻' : 'Pi','屁' : 'Pi','譬' : 'Pi','丕' : 'Pi','仳' : 'Pi','陴' : 'Pi','邳' : 'Pi','郫' : 'Pi','圮' : 'Pi','埤' : 'Pi','鼙' : 'Pi','芘' : 'Pi','擗' : 'Pi','噼' : 'Pi','庀' : 'Pi','淠' : 'Pi','媲' : 'Pi','纰' : 'Pi','枇' : 'Pi','甓' : 'Pi','罴' : 'Pi','铍' : 'Pi','癖' : 'Pi','疋' : 'Pi','蚍' : 'Pi','蜱' : 'Pi','貔' : 'Pi',
'鞭' : 'Bian','边' : 'Bian','编' : 'Bian','贬' : 'Bian','扁' : 'Bian','便' : 'Bian','变' : 'Bian','卞' : 'Bian','辨' : 'Bian','辩' : 'Bian','辫' : 'Bian','遍' : 'Bian','匾' : 'Bian','弁' : 'Bian','苄' : 'Bian','忭' : 'Bian','汴' : 'Bian','缏' : 'Bian','煸' : 'Bian','砭' : 'Bian','碥' : 'Bian','窆' : 'Bian','褊' : 'Bian','蝙' : 'Bian','笾' : 'Bian','鳊' : 'Bian',
'标' : 'Biao','彪' : 'Biao','膘' : 'Biao','表' : 'Biao','婊' : 'Biao','骠' : 'Biao','飑' : 'Biao','飙' : 'Biao','飚' : 'Biao','镖' : 'Biao','镳' : 'Biao','瘭' : 'Biao','裱' : 'Biao','鳔' : 'Biao',
'鳖' : 'Bie','憋' : 'Bie','别' : 'Bie','瘪' : 'Bie','蹩' : 'Bie',
'彬' : 'Bin','斌' : 'Bin','濒' : 'Bin','滨' : 'Bin','宾' : 'Bin','摈' : 'Bin','傧' : 'Bin','豳' : 'Bin','缤' : 'Bin','玢' : 'Bin','槟' : 'Bin','殡' : 'Bin','膑' : 'Bin','镔' : 'Bin','髌' : 'Bin','鬓' : 'Bin',
'兵' : 'Bing','冰' : 'Bing','柄' : 'Bing','丙' : 'Bing','秉' : 'Bing','饼' : 'Bing','炳' : 'Bing','病' : 'Bing','并' : 'Bing','禀' : 'Bing','邴' : 'Bing','摒' : 'Bing',
'捕' : 'Bu','卜' : 'Bu','哺' : 'Bu','补' : 'Bu','埠' : 'Bu','不' : 'Bu','布' : 'Bu','步' : 'Bu','簿' : 'Bu','部' : 'Bu','怖' : 'Bu','卟' : 'Bu','逋' : 'Bu','瓿' : 'Bu','晡' : 'Bu','钚' : 'Bu','钸' : 'Bu','醭' : 'Bu',
'擦' : 'Ca','嚓' : 'Ca','礤' : 'Ca',
'猜' : 'Cai','裁' : 'Cai','材' : 'Cai','才' : 'Cai','财' : 'Cai','睬' : 'Cai','踩' : 'Cai','采' : 'Cai','彩' : 'Cai','菜' : 'Cai','蔡' : 'Cai',
'餐' : 'Can','参' : 'Can','蚕' : 'Can','残' : 'Can','惭' : 'Can','惨' : 'Can','灿' : 'Can','骖' : 'Can','璨' : 'Can','粲' : 'Can','黪' : 'Can',
'苍' : 'Cang','舱' : 'Cang','仓' : 'Cang','沧' : 'Cang','藏' : 'Cang','伧' : 'Cang',
'操' : 'Cao','糙' : 'Cao','槽' : 'Cao','曹' : 'Cao','草' : 'Cao','嘈' : 'Cao','漕' : 'Cao','螬' : 'Cao','艚' : 'Cao',
'厕' : 'Ce','策' : 'Ce','侧' : 'Ce','册' : 'Ce','测' : 'Ce','恻' : 'Ce',
'层' : 'Ceng','蹭' : 'Ceng','曾' : 'Ceng','噌' : 'Ceng',
'插' : 'Cha','叉' : 'Cha','茬' : 'Cha','茶' : 'Cha','查' : 'Cha','碴' : 'Cha','搽' : 'Cha','察' : 'Cha','岔' : 'Cha','诧' : 'Cha','猹' : 'Cha','馇' : 'Cha','汊' : 'Cha','姹' : 'Cha','杈' : 'Cha','槎' : 'Cha','檫' : 'Cha','锸' : 'Cha','镲' : 'Cha','衩' : 'Cha',
'差' : 'Chai','拆' : 'Chai','柴' : 'Chai','豺' : 'Chai','侪' : 'Chai','钗' : 'Chai','瘥' : 'Chai','虿' : 'Chai',
'搀' : 'Chan','掺' : 'Chan','蝉' : 'Chan','馋' : 'Chan','谗' : 'Chan','缠' : 'Chan','铲' : 'Chan','产' : 'Chan','阐' : 'Chan','颤' : 'Chan','冁' : 'Chan','谄' : 'Chan','蒇' : 'Chan','廛' : 'Chan','忏' : 'Chan','潺' : 'Chan','澶' : 'Chan','孱' : 'Chan','羼' : 'Chan','婵' : 'Chan','骣' : 'Chan','觇' : 'Chan','禅' : 'Chan','蟾' : 'Chan','躔' : 'Chan',
'昌' : 'Chang','猖' : 'Chang','场' : 'Chang','尝' : 'Chang','常' : 'Chang','长' : 'Chang','偿' : 'Chang','肠' : 'Chang','厂' : 'Chang','敞' : 'Chang','畅' : 'Chang','唱' : 'Chang','倡' : 'Chang','伥' : 'Chang','鬯' : 'Chang','苌' : 'Chang','菖' : 'Chang','徜' : 'Chang','怅' : 'Chang','惝' : 'Chang','阊' : 'Chang','娼' : 'Chang','嫦' : 'Chang','昶' : 'Chang','氅' : 'Chang','鲳' : 'Chang',
'超' : 'Chao','抄' : 'Chao','钞' : 'Chao','朝' : 'Chao','嘲' : 'Chao','潮' : 'Chao','巢' : 'Chao','吵' : 'Chao','炒' : 'Chao','怊' : 'Chao','晁' : 'Chao','焯' : 'Chao','耖' : 'Chao',
'车' : 'Che','扯' : 'Che','撤' : 'Che','掣' : 'Che','彻' : 'Che','澈' : 'Che','坼' : 'Che','砗' : 'Che',
'郴' : 'Chen','臣' : 'Chen','辰' : 'Chen','尘' : 'Chen','晨' : 'Chen','忱' : 'Chen','沉' : 'Chen','陈' : 'Chen','趁' : 'Chen','衬' : 'Chen','谌' : 'Chen','谶' : 'Chen','抻' : 'Chen','嗔' : 'Chen','宸' : 'Chen','琛' : 'Chen','榇' : 'Chen','碜' : 'Chen','龀' : 'Chen',
'撑' : 'Cheng','称' : 'Cheng','城' : 'Cheng','橙' : 'Cheng','成' : 'Cheng','呈' : 'Cheng','乘' : 'Cheng','程' : 'Cheng','惩' : 'Cheng','澄' : 'Cheng','诚' : 'Cheng','承' : 'Cheng','逞' : 'Cheng','骋' : 'Cheng','秤' : 'Cheng','丞' : 'Cheng','埕' : 'Cheng','枨' : 'Cheng','柽' : 'Cheng','塍' : 'Cheng','瞠' : 'Cheng','铖' : 'Cheng','铛' : 'Cheng','裎' : 'Cheng','蛏' : 'Cheng','酲' : 'Cheng',
'吃' : 'Chi','痴' : 'Chi','持' : 'Chi','池' : 'Chi','迟' : 'Chi','弛' : 'Chi','驰' : 'Chi','耻' : 'Chi','齿' : 'Chi','侈' : 'Chi','尺' : 'Chi','赤' : 'Chi','翅' : 'Chi','斥' : 'Chi','炽' : 'Chi','傺' : 'Chi','墀' : 'Chi','茌' : 'Chi','叱' : 'Chi','哧' : 'Chi','啻' : 'Chi','嗤' : 'Chi','彳' : 'Chi','饬' : 'Chi','媸' : 'Chi','敕' : 'Chi','眵' : 'Chi','鸱' : 'Chi','瘛' : 'Chi','褫' : 'Chi','蚩' : 'Chi','螭' : 'Chi','笞' : 'Chi','篪' : 'Chi','豉' : 'Chi','踟' : 'Chi','魑' : 'Chi',
'匙' : 'Shi','师' : 'Shi','失' : 'Shi','狮' : 'Shi','施' : 'Shi','湿' : 'Shi','诗' : 'Shi','尸' : 'Shi','虱' : 'Shi','十' : 'Shi','石' : 'Shi','拾' : 'Shi','时' : 'Shi','食' : 'Shi','蚀' : 'Shi','实' : 'Shi','识' : 'Shi','史' : 'Shi','矢' : 'Shi','使' : 'Shi','屎' : 'Shi','驶' : 'Shi','始' : 'Shi','式' : 'Shi','示' : 'Shi','士' : 'Shi','世' : 'Shi','柿' : 'Shi','事' : 'Shi','拭' : 'Shi','誓' : 'Shi','逝' : 'Shi','势' : 'Shi','是' : 'Shi','嗜' : 'Shi','噬' : 'Shi','适' : 'Shi','仕' : 'Shi','侍' : 'Shi','释' : 'Shi','饰' : 'Shi','氏' : 'Shi','市' : 'Shi','恃' : 'Shi','室' : 'Shi','视' : 'Shi','试' : 'Shi','谥' : 'Shi','埘' : 'Shi','莳' : 'Shi','蓍' : 'Shi','弑' : 'Shi','轼' : 'Shi','贳' : 'Shi','炻' : 'Shi','礻' : 'Shi','铈' : 'Shi','舐' : 'Shi','筮' : 'Shi','豕' : 'Shi','鲥' : 'Shi','鲺' : 'Shi',
'充' : 'Chong','冲' : 'Chong','虫' : 'Chong','崇' : 'Chong','宠' : 'Chong','重' : 'Chong','茺' : 'Chong','忡' : 'Chong','憧' : 'Chong','铳' : 'Chong','舂' : 'Chong','艟' : 'Chong',
'抽' : 'Chou','酬' : 'Chou','畴' : 'Chou','踌' : 'Chou','稠' : 'Chou','愁' : 'Chou','筹' : 'Chou','仇' : 'Chou','绸' : 'Chou','瞅' : 'Chou','丑' : 'Chou','臭' : 'Chou','俦' : 'Chou','帱' : 'Chou','惆' : 'Chou','瘳' : 'Chou','雠' : 'Chou',
'初' : 'Chu','出' : 'Chu','橱' : 'Chu','厨' : 'Chu','躇' : 'Chu','锄' : 'Chu','雏' : 'Chu','滁' : 'Chu','除' : 'Chu','楚' : 'Chu','础' : 'Chu','储' : 'Chu','矗' : 'Chu','搐' : 'Chu','触' : 'Chu','处' : 'Chu','亍' : 'Chu','刍' : 'Chu','怵' : 'Chu','憷' : 'Chu','绌' : 'Chu','杵' : 'Chu','楮' : 'Chu','樗' : 'Chu','褚' : 'Chu','蜍' : 'Chu','蹰' : 'Chu','黜' : 'Chu',
'揣' : 'Chuai','搋' : 'Chuai','嘬' : 'Chuai','膪' : 'Chuai','踹' : 'Chuai',
'川' : 'Chuan','穿' : 'Chuan','椽' : 'Chuan','传' : 'Chuan','船' : 'Chuan','喘' : 'Chuan','串' : 'Chuan','舛' : 'Chuan','遄' : 'Chuan','氚' : 'Chuan','钏' : 'Chuan','舡' : 'Chuan',
'疮' : 'Chuang','窗' : 'Chuang','床' : 'Chuang','闯' : 'Chuang','创' : 'Chuang','怆' : 'Chuang',
'幢' : 'Zhuang','桩' : 'Zhuang','庄' : 'Zhuang','装' : 'Zhuang','妆' : 'Zhuang','撞' : 'Zhuang','壮' : 'Zhuang','状' : 'Zhuang','僮' : 'Zhuang',
'吹' : 'Chui','炊' : 'Chui','捶' : 'Chui','锤' : 'Chui','垂' : 'Chui','陲' : 'Chui','棰' : 'Chui','槌' : 'Chui',
'春' : 'Chun','椿' : 'Chun','醇' : 'Chun','唇' : 'Chun','淳' : 'Chun','纯' : 'Chun','蠢' : 'Chun','莼' : 'Chun','鹑' : 'Chun','蝽' : 'Chun',
'戳' : 'Chuo','绰' : 'Chuo','啜' : 'Chuo','辍' : 'Chuo','踔' : 'Chuo','龊' : 'Chuo',
'疵' : 'Ci','茨' : 'Ci','磁' : 'Ci','雌' : 'Ci','辞' : 'Ci','慈' : 'Ci','瓷' : 'Ci','词' : 'Ci','此' : 'Ci','刺' : 'Ci','赐' : 'Ci','次' : 'Ci','茈' : 'Ci','祠' : 'Ci','鹚' : 'Ci','糍' : 'Ci',
'聪' : 'Cong','葱' : 'Cong','囱' : 'Cong','匆' : 'Cong','从' : 'Cong','丛' : 'Cong','苁' : 'Cong','淙' : 'Cong','骢' : 'Cong','琮' : 'Cong','璁' : 'Cong','枞' : 'Cong',
'凑' : 'Cou','楱' : 'Cou','辏' : 'Cou','腠' : 'Cou',
'粗' : 'Cu','醋' : 'Cu','簇' : 'Cu','促' : 'Cu','卒' : 'Cu','蔟' : 'Cu','徂' : 'Cu','猝' : 'Cu','殂' : 'Cu','酢' : 'Cu','蹙' : 'Cu','蹴' : 'Cu',
'蹿' : 'Cuan','篡' : 'Cuan','窜' : 'Cuan','汆' : 'Cuan','撺' : 'Cuan','爨' : 'Cuan','镩' : 'Cuan',
'摧' : 'Cui','崔' : 'Cui','催' : 'Cui','脆' : 'Cui','瘁' : 'Cui','粹' : 'Cui','淬' : 'Cui','翠' : 'Cui','萃' : 'Cui','啐' : 'Cui','悴' : 'Cui','璀' : 'Cui','榱' : 'Cui','毳' : 'Cui',
'村' : 'Cun','存' : 'Cun','寸' : 'Cun','忖' : 'Cun','皴' : 'Cun',
'磋' : 'Cuo','撮' : 'Cuo','搓' : 'Cuo','措' : 'Cuo','挫' : 'Cuo','错' : 'Cuo','厝' : 'Cuo','嵯' : 'Cuo','脞' : 'Cuo','锉' : 'Cuo','矬' : 'Cuo','痤' : 'Cuo','鹾' : 'Cuo','蹉' : 'Cuo',
'搭' : 'Da','达' : 'Da','答' : 'Da','瘩' : 'Da','打' : 'Da','大' : 'Da','耷' : 'Da','哒' : 'Da','怛' : 'Da','妲' : 'Da','褡' : 'Da','笪' : 'Da','靼' : 'Da','鞑' : 'Da',
'呆' : 'Dai','歹' : 'Dai','傣' : 'Dai','戴' : 'Dai','带' : 'Dai','殆' : 'Dai','代' : 'Dai','贷' : 'Dai','袋' : 'Dai','待' : 'Dai','逮' : 'Dai','怠' : 'Dai','埭' : 'Dai','甙' : 'Dai','呔' : 'Dai','岱' : 'Dai','迨' : 'Dai','绐' : 'Dai','玳' : 'Dai','黛' : 'Dai',
'耽' : 'Dan','担' : 'Dan','丹' : 'Dan','单' : 'Dan','郸' : 'Dan','掸' : 'Dan','胆' : 'Dan','旦' : 'Dan','氮' : 'Dan','但' : 'Dan','惮' : 'Dan','淡' : 'Dan','诞' : 'Dan','蛋' : 'Dan','儋' : 'Dan','凼' : 'Dan','萏' : 'Dan','菪' : 'Dan','啖' : 'Dan','澹' : 'Dan','宕' : 'Dan','殚' : 'Dan','赕' : 'Dan','眈' : 'Dan','疸' : 'Dan','瘅' : 'Dan','聃' : 'Dan','箪' : 'Dan',
'弹' : 'Tan','坍' : 'Tan','摊' : 'Tan','贪' : 'Tan','瘫' : 'Tan','滩' : 'Tan','坛' : 'Tan','檀' : 'Tan','痰' : 'Tan','潭' : 'Tan','谭' : 'Tan','谈' : 'Tan','坦' : 'Tan','毯' : 'Tan','袒' : 'Tan','碳' : 'Tan','探' : 'Tan','叹' : 'Tan','炭' : 'Tan','郯' : 'Tan','昙' : 'Tan','忐' : 'Tan','钽' : 'Tan','锬' : 'Tan','覃' : 'Tan',
'当' : 'Dang','挡' : 'Dang','党' : 'Dang','荡' : 'Dang','档' : 'Dang','谠' : 'Dang','砀' : 'Dang','裆' : 'Dang',
'刀' : 'Dao','捣' : 'Dao','蹈' : 'Dao','倒' : 'Dao','岛' : 'Dao','祷' : 'Dao','导' : 'Dao','到' : 'Dao','稻' : 'Dao','悼' : 'Dao','道' : 'Dao','盗' : 'Dao','叨' : 'Dao','氘' : 'Dao','焘' : 'Dao','纛' : 'Dao',
'德' : 'De','得' : 'De','的' : 'De','锝' : 'De',
'蹬' : 'Deng','灯' : 'Deng','登' : 'Deng','等' : 'Deng','瞪' : 'Deng','凳' : 'Deng','邓' : 'Deng','噔' : 'Deng','嶝' : 'Deng','戥' : 'Deng','磴' : 'Deng','镫' : 'Deng','簦' : 'Deng',
'堤' : 'Di','低' : 'Di','滴' : 'Di','迪' : 'Di','敌' : 'Di','笛' : 'Di','狄' : 'Di','涤' : 'Di','嫡' : 'Di','抵' : 'Di','底' : 'Di','地' : 'Di','蒂' : 'Di','第' : 'Di','帝' : 'Di','弟' : 'Di','递' : 'Di','缔' : 'Di','氐' : 'Di','籴' : 'Di','诋' : 'Di','谛' : 'Di','邸' : 'Di','坻' : 'Di','荻' : 'Di','嘀' : 'Di','娣' : 'Di','柢' : 'Di','棣' : 'Di','觌' : 'Di','祗' : 'Di','砥' : 'Di','碲' : 'Di','睇' : 'Di','镝' : 'Di','羝' : 'Di','骶' : 'Di',
'翟' : 'Zhai','摘' : 'Zhai','斋' : 'Zhai','宅' : 'Zhai','窄' : 'Zhai','债' : 'Zhai','寨' : 'Zhai','砦' : 'Zhai','瘵' : 'Zhai',
'颠' : 'Dian','掂' : 'Dian','滇' : 'Dian','碘' : 'Dian','点' : 'Dian','典' : 'Dian','靛' : 'Dian','垫' : 'Dian','电' : 'Dian','佃' : 'Dian','甸' : 'Dian','店' : 'Dian','惦' : 'Dian','奠' : 'Dian','淀' : 'Dian','殿' : 'Dian','丶' : 'Dian','阽' : 'Dian','坫' : 'Dian','巅' : 'Dian','玷' : 'Dian','钿' : 'Dian','癜' : 'Dian','癫' : 'Dian','簟' : 'Dian','踮' : 'Dian',
'碉' : 'Diao','叼' : 'Diao','雕' : 'Diao','凋' : 'Diao','刁' : 'Diao','掉' : 'Diao','吊' : 'Diao','钓' : 'Diao','铞' : 'Diao','貂' : 'Diao','鲷' : 'Diao',
'调' : 'Tiao','挑' : 'Tiao','条' : 'Tiao','迢' : 'Tiao','眺' : 'Tiao','跳' : 'Tiao','佻' : 'Tiao','苕' : 'Tiao','祧' : 'Tiao','窕' : 'Tiao','蜩' : 'Tiao','笤' : 'Tiao','粜' : 'Tiao','龆' : 'Tiao','鲦' : 'Tiao','髫' : 'Tiao',
'跌' : 'Die','爹' : 'Die','碟' : 'Die','蝶' : 'Die','迭' : 'Die','谍' : 'Die','叠' : 'Die','垤' : 'Die','堞' : 'Die','喋' : 'Die','牒' : 'Die','瓞' : 'Die','耋' : 'Die','鲽' : 'Die',
'丁' : 'Ding','盯' : 'Ding','叮' : 'Ding','钉' : 'Ding','顶' : 'Ding','鼎' : 'Ding','锭' : 'Ding','定' : 'Ding','订' : 'Ding','仃' : 'Ding','啶' : 'Ding','玎' : 'Ding','腚' : 'Ding','碇' : 'Ding','町' : 'Ding','疔' : 'Ding','耵' : 'Ding','酊' : 'Ding',
'丢' : 'Diu','铥' : 'Diu',
'东' : 'Dong','冬' : 'Dong','董' : 'Dong','懂' : 'Dong','动' : 'Dong','栋' : 'Dong','侗' : 'Dong','恫' : 'Dong','冻' : 'Dong','洞' : 'Dong','垌' : 'Dong','咚' : 'Dong','岽' : 'Dong','峒' : 'Dong','氡' : 'Dong','胨' : 'Dong','胴' : 'Dong','硐' : 'Dong','鸫' : 'Dong',
'兜' : 'Dou','抖' : 'Dou','斗' : 'Dou','陡' : 'Dou','豆' : 'Dou','逗' : 'Dou','痘' : 'Dou','蔸' : 'Dou','钭' : 'Dou','窦' : 'Dou','蚪' : 'Dou','篼' : 'Dou',
'都' : 'Du','督' : 'Du','毒' : 'Du','犊' : 'Du','独' : 'Du','读' : 'Du','堵' : 'Du','睹' : 'Du','赌' : 'Du','杜' : 'Du','镀' : 'Du','肚' : 'Du','度' : 'Du','渡' : 'Du','妒' : 'Du','芏' : 'Du','嘟' : 'Du','渎' : 'Du','椟' : 'Du','牍' : 'Du','蠹' : 'Du','笃' : 'Du','髑' : 'Du','黩' : 'Du',
'端' : 'Duan','短' : 'Duan','锻' : 'Duan','段' : 'Duan','断' : 'Duan','缎' : 'Duan','椴' : 'Duan','煅' : 'Duan','簖' : 'Duan',
'堆' : 'Dui','兑' : 'Dui','队' : 'Dui','对' : 'Dui','怼' : 'Dui','憝' : 'Dui','碓' : 'Dui','镦' : 'Dui',
'墩' : 'Dun','吨' : 'Dun','蹲' : 'Dun','敦' : 'Dun','顿' : 'Dun','钝' : 'Dun','盾' : 'Dun','遁' : 'Dun','沌' : 'Dun','炖' : 'Dun','砘' : 'Dun','礅' : 'Dun','盹' : 'Dun','趸' : 'Dun',
'囤' : 'Tun','吞' : 'Tun','屯' : 'Tun','臀' : 'Tun','氽' : 'Tun','饨' : 'Tun','暾' : 'Tun','豚' : 'Tun',
'掇' : 'Duo','哆' : 'Duo','多' : 'Duo','夺' : 'Duo','垛' : 'Duo','躲' : 'Duo','朵' : 'Duo','跺' : 'Duo','舵' : 'Duo','剁' : 'Duo','惰' : 'Duo','堕' : 'Duo','咄' : 'Duo','哚' : 'Duo','沲' : 'Duo','缍' : 'Duo','铎' : 'Duo','裰' : 'Duo','踱' : 'Duo',
'蛾' : 'E','峨' : 'E','鹅' : 'E','俄' : 'E','额' : 'E','讹' : 'E','娥' : 'E','恶' : 'E','厄' : 'E','扼' : 'E','遏' : 'E','鄂' : 'E','饿' : 'E','噩' : 'E','谔' : 'E','垩' : 'E','苊' : 'E','莪' : 'E','萼' : 'E','呃' : 'E','愕' : 'E','屙' : 'E','婀' : 'E','轭' : 'E','腭' : 'E','锇' : 'E','锷' : 'E','鹗' : 'E','颚' : 'E','鳄' : 'E',
'恩' : 'En','蒽' : 'En','摁' : 'En','嗯' : 'En',
'而' : 'Er','儿' : 'Er','耳' : 'Er','尔' : 'Er','饵' : 'Er','洱' : 'Er','二' : 'Er','贰' : 'Er','迩' : 'Er','珥' : 'Er','铒' : 'Er','鸸' : 'Er','鲕' : 'Er',
'发' : 'Fa','罚' : 'Fa','筏' : 'Fa','伐' : 'Fa','乏' : 'Fa','阀' : 'Fa','法' : 'Fa','珐' : 'Fa','垡' : 'Fa','砝' : 'Fa',
'藩' : 'Fan','帆' : 'Fan','番' : 'Fan','翻' : 'Fan','樊' : 'Fan','矾' : 'Fan','钒' : 'Fan','繁' : 'Fan','凡' : 'Fan','烦' : 'Fan','反' : 'Fan','返' : 'Fan','范' : 'Fan','贩' : 'Fan','犯' : 'Fan','饭' : 'Fan','泛' : 'Fan','蕃' : 'Fan','蘩' : 'Fan','幡' : 'Fan','夂' : 'Fan','梵' : 'Fan','燔' : 'Fan','畈' : 'Fan','蹯' : 'Fan',
'坊' : 'Fang','芳' : 'Fang','方' : 'Fang','肪' : 'Fang','房' : 'Fang','防' : 'Fang','妨' : 'Fang','仿' : 'Fang','访' : 'Fang','纺' : 'Fang','放' : 'Fang','邡' : 'Fang','枋' : 'Fang','钫' : 'Fang','舫' : 'Fang','鲂' : 'Fang',
'菲' : 'Fei','非' : 'Fei','啡' : 'Fei','飞' : 'Fei','肥' : 'Fei','匪' : 'Fei','诽' : 'Fei','吠' : 'Fei','肺' : 'Fei','废' : 'Fei','沸' : 'Fei','费' : 'Fei','狒' : 'Fei','悱' : 'Fei','淝' : 'Fei','妃' : 'Fei','绯' : 'Fei','榧' : 'Fei','腓' : 'Fei','斐' : 'Fei','扉' : 'Fei','砩' : 'Fei','镄' : 'Fei','痱' : 'Fei','蜚' : 'Fei','篚' : 'Fei','翡' : 'Fei','霏' : 'Fei','鲱' : 'Fei',
'芬' : 'Fen','酚' : 'Fen','吩' : 'Fen','氛' : 'Fen','分' : 'Fen','纷' : 'Fen','坟' : 'Fen','焚' : 'Fen','汾' : 'Fen','粉' : 'Fen','奋' : 'Fen','份' : 'Fen','忿' : 'Fen','愤' : 'Fen','粪' : 'Fen','偾' : 'Fen','瀵' : 'Fen','棼' : 'Fen','鲼' : 'Fen','鼢' : 'Fen',
'丰' : 'Feng','封' : 'Feng','枫' : 'Feng','蜂' : 'Feng','峰' : 'Feng','锋' : 'Feng','风' : 'Feng','疯' : 'Feng','烽' : 'Feng','逢' : 'Feng','冯' : 'Feng','缝' : 'Feng','讽' : 'Feng','奉' : 'Feng','凤' : 'Feng','俸' : 'Feng','酆' : 'Feng','葑' : 'Feng','唪' : 'Feng','沣' : 'Feng','砜' : 'Feng',
'佛' : 'Fo',
'否' : 'Fou','缶' : 'Fou',
'夫' : 'Fu','敷' : 'Fu','肤' : 'Fu','孵' : 'Fu','扶' : 'Fu','拂' : 'Fu','辐' : 'Fu','幅' : 'Fu','氟' : 'Fu','符' : 'Fu','伏' : 'Fu','俘' : 'Fu','服' : 'Fu','浮' : 'Fu','涪' : 'Fu','福' : 'Fu','袱' : 'Fu','弗' : 'Fu','甫' : 'Fu','抚' : 'Fu','辅' : 'Fu','俯' : 'Fu','釜' : 'Fu','斧' : 'Fu','脯' : 'Fu','腑' : 'Fu','府' : 'Fu','腐' : 'Fu','赴' : 'Fu','副' : 'Fu','覆' : 'Fu','赋' : 'Fu','复' : 'Fu','傅' : 'Fu','付' : 'Fu','阜' : 'Fu','父' : 'Fu','腹' : 'Fu','负' : 'Fu','富' : 'Fu','讣' : 'Fu','附' : 'Fu','妇' : 'Fu','缚' : 'Fu','咐' : 'Fu','匐' : 'Fu','凫' : 'Fu','郛' : 'Fu','芙' : 'Fu','芾' : 'Fu','苻' : 'Fu','茯' : 'Fu','莩' : 'Fu','菔' : 'Fu','拊' : 'Fu','呋' : 'Fu','呒' : 'Fu','幞' : 'Fu','怫' : 'Fu','滏' : 'Fu','艴' : 'Fu','孚' : 'Fu','驸' : 'Fu','绂' : 'Fu','绋' : 'Fu','桴' : 'Fu','赙' : 'Fu','祓' : 'Fu','黻' : 'Fu','黼' : 'Fu','罘' : 'Fu','稃' : 'Fu','馥' : 'Fu','蚨' : 'Fu','蜉' : 'Fu','蝠' : 'Fu','蝮' : 'Fu','麸' : 'Fu','趺' : 'Fu','跗' : 'Fu','鲋' : 'Fu','鳆' : 'Fu',
'噶' : 'Ga','嘎' : 'Ga','垓' : 'Ga','尬' : 'Ga','尕' : 'Ga','尜' : 'Ga','旮' : 'Ga','钆' : 'Ga',
'该' : 'Gai','改' : 'Gai','概' : 'Gai','钙' : 'Gai','盖' : 'Gai','溉' : 'Gai','丐' : 'Gai','陔' : 'Gai','戤' : 'Gai','赅' : 'Gai',
'干' : 'Gan','甘' : 'Gan','杆' : 'Gan','柑' : 'Gan','竿' : 'Gan','肝' : 'Gan','赶' : 'Gan','感' : 'Gan','秆' : 'Gan','敢' : 'Gan','赣' : 'Gan','坩' : 'Gan','苷' : 'Gan','尴' : 'Gan','擀' : 'Gan','泔' : 'Gan','淦' : 'Gan','澉' : 'Gan','绀' : 'Gan','橄' : 'Gan','旰' : 'Gan','矸' : 'Gan','疳' : 'Gan','酐' : 'Gan',
'冈' : 'Gang','刚' : 'Gang','钢' : 'Gang','缸' : 'Gang','肛' : 'Gang','纲' : 'Gang','岗' : 'Gang','港' : 'Gang','杠' : 'Gang','戆' : 'Gang','罡' : 'Gang','筻' : 'Gang',
'篙' : 'Gao','皋' : 'Gao','高' : 'Gao','膏' : 'Gao','羔' : 'Gao','糕' : 'Gao','搞' : 'Gao','镐' : 'Gao','稿' : 'Gao','告' : 'Gao','睾' : 'Gao','诰' : 'Gao','郜' : 'Gao','藁' : 'Gao','缟' : 'Gao','槔' : 'Gao','槁' : 'Gao','杲' : 'Gao','锆' : 'Gao',
'哥' : 'Ge','歌' : 'Ge','搁' : 'Ge','戈' : 'Ge','鸽' : 'Ge','胳' : 'Ge','疙' : 'Ge','割' : 'Ge','革' : 'Ge','葛' : 'Ge','格' : 'Ge','阁' : 'Ge','隔' : 'Ge','铬' : 'Ge','个' : 'Ge','各' : 'Ge','鬲' : 'Ge','仡' : 'Ge','哿' : 'Ge','圪' : 'Ge','塥' : 'Ge','嗝' : 'Ge','纥' : 'Ge','搿' : 'Ge','膈' : 'Ge','硌' : 'Ge','镉' : 'Ge','袼' : 'Ge','虼' : 'Ge','舸' : 'Ge','骼' : 'Ge',
'蛤' : 'Ha','哈' : 'Ha','铪' : 'Ha',
'给' : 'Gei',
'根' : 'Gen','跟' : 'Gen','亘' : 'Gen','茛' : 'Gen','哏' : 'Gen','艮' : 'Gen',
'耕' : 'Geng','更' : 'Geng','庚' : 'Geng','羹' : 'Geng','埂' : 'Geng','耿' : 'Geng','梗' : 'Geng','哽' : 'Geng','赓' : 'Geng','绠' : 'Geng','鲠' : 'Geng',
'工' : 'Gong','攻' : 'Gong','功' : 'Gong','恭' : 'Gong','龚' : 'Gong','供' : 'Gong','躬' : 'Gong','公' : 'Gong','宫' : 'Gong','弓' : 'Gong','巩' : 'Gong','汞' : 'Gong','拱' : 'Gong','贡' : 'Gong','共' : 'Gong','珙' : 'Gong','肱' : 'Gong','蚣' : 'Gong','觥' : 'Gong',
'钩' : 'Gou','勾' : 'Gou','沟' : 'Gou','苟' : 'Gou','狗' : 'Gou','垢' : 'Gou','构' : 'Gou','购' : 'Gou','够' : 'Gou','佝' : 'Gou','诟' : 'Gou','岣' : 'Gou','遘' : 'Gou','媾' : 'Gou','缑' : 'Gou','枸' : 'Gou','觏' : 'Gou','彀' : 'Gou','笱' : 'Gou','篝' : 'Gou','鞲' : 'Gou',
'辜' : 'Gu','菇' : 'Gu','咕' : 'Gu','箍' : 'Gu','估' : 'Gu','沽' : 'Gu','孤' : 'Gu','姑' : 'Gu','鼓' : 'Gu','古' : 'Gu','蛊' : 'Gu','骨' : 'Gu','谷' : 'Gu','股' : 'Gu','故' : 'Gu','顾' : 'Gu','固' : 'Gu','雇' : 'Gu','嘏' : 'Gu','诂' : 'Gu','菰' : 'Gu','崮' : 'Gu','汩' : 'Gu','梏' : 'Gu','轱' : 'Gu','牯' : 'Gu','牿' : 'Gu','臌' : 'Gu','毂' : 'Gu','瞽' : 'Gu','罟' : 'Gu','钴' : 'Gu','锢' : 'Gu','鸪' : 'Gu','痼' : 'Gu','蛄' : 'Gu','酤' : 'Gu','觚' : 'Gu','鲴' : 'Gu',
'刮' : 'Gua','瓜' : 'Gua','剐' : 'Gua','寡' : 'Gua','挂' : 'Gua','褂' : 'Gua','卦' : 'Gua','诖' : 'Gua','呱' : 'Gua','栝' : 'Gua','胍' : 'Gua','鸹' : 'Gua',
'乖' : 'Guai','拐' : 'Guai','怪' : 'Guai','掴' : 'Guai',
'棺' : 'Guan','关' : 'Guan','官' : 'Guan','冠' : 'Guan','观' : 'Guan','管' : 'Guan','馆' : 'Guan','罐' : 'Guan','惯' : 'Guan','灌' : 'Guan','贯' : 'Guan','倌' : 'Guan','莞' : 'Guan','掼' : 'Guan','涫' : 'Guan','盥' : 'Guan','鹳' : 'Guan','鳏' : 'Guan',
'光' : 'Guang','广' : 'Guang','逛' : 'Guang','咣' : 'Guang','犷' : 'Guang','桄' : 'Guang','胱' : 'Guang',
'瑰' : 'Gui','规' : 'Gui','圭' : 'Gui','硅' : 'Gui','归' : 'Gui','龟' : 'Gui','闺' : 'Gui','轨' : 'Gui','鬼' : 'Gui','诡' : 'Gui','癸' : 'Gui','桂' : 'Gui','柜' : 'Gui','跪' : 'Gui','贵' : 'Gui','刽' : 'Gui','匦' : 'Gui','刿' : 'Gui','庋' : 'Gui','宄' : 'Gui','妫' : 'Gui','桧' : 'Gui','炅' : 'Gui','晷' : 'Gui','皈' : 'Gui','簋' : 'Gui','鲑' : 'Gui','鳜' : 'Gui',
'辊' : 'Gun','滚' : 'Gun','棍' : 'Gun','衮' : 'Gun','绲' : 'Gun','磙' : 'Gun','鲧' : 'Gun',
'锅' : 'Guo','郭' : 'Guo','国' : 'Guo','果' : 'Guo','裹' : 'Guo','过' : 'Guo','馘' : 'Guo','埚' : 'Guo','呙' : 'Guo','帼' : 'Guo','崞' : 'Guo','猓' : 'Guo','椁' : 'Guo','虢' : 'Guo','聒' : 'Guo','蜾' : 'Guo','蝈' : 'Guo',
'骸' : 'Hai','孩' : 'Hai','海' : 'Hai','氦' : 'Hai','亥' : 'Hai','害' : 'Hai','骇' : 'Hai','嗨' : 'Hai','胲' : 'Hai','醢' : 'Hai',
'酣' : 'Han','憨' : 'Han','邯' : 'Han','韩' : 'Han','含' : 'Han','涵' : 'Han','寒' : 'Han','函' : 'Han','喊' : 'Han','罕' : 'Han','翰' : 'Han','撼' : 'Han','捍' : 'Han','旱' : 'Han','憾' : 'Han','悍' : 'Han','焊' : 'Han','汗' : 'Han','汉' : 'Han','邗' : 'Han','菡' : 'Han','撖' : 'Han','犴' : 'Han','瀚' : 'Han','晗' : 'Han','焓' : 'Han','顸' : 'Han','颔' : 'Han','蚶' : 'Han','鼾' : 'Han',
'夯' : 'Hang','杭' : 'Hang','航' : 'Hang','行' : 'Hang','沆' : 'Hang','绗' : 'Hang','颃' : 'Hang',
'壕' : 'Hao','嚎' : 'Hao','豪' : 'Hao','毫' : 'Hao','郝' : 'Hao','好' : 'Hao','耗' : 'Hao','号' : 'Hao','浩' : 'Hao','貉' : 'Hao','蒿' : 'Hao','薅' : 'Hao','嗥' : 'Hao','嚆' : 'Hao','濠' : 'Hao','灏' : 'Hao','昊' : 'Hao','皓' : 'Hao','颢' : 'Hao','蚝' : 'Hao',
'呵' : 'He','喝' : 'He','荷' : 'He','菏' : 'He','核' : 'He','禾' : 'He','和' : 'He','何' : 'He','合' : 'He','盒' : 'He','阂' : 'He','河' : 'He','涸' : 'He','赫' : 'He','褐' : 'He','鹤' : 'He','贺' : 'He','诃' : 'He','劾' : 'He','壑' : 'He','嗬' : 'He','阖' : 'He','曷' : 'He','盍' : 'He','颌' : 'He','蚵' : 'He','翮' : 'He',
'嘿' : 'Hei','黑' : 'Hei',
'痕' : 'Hen','很' : 'Hen','狠' : 'Hen','恨' : 'Hen',
'哼' : 'Heng','亨' : 'Heng','横' : 'Heng','衡' : 'Heng','恒' : 'Heng','蘅' : 'Heng','珩' : 'Heng','桁' : 'Heng',
'轰' : 'Hong','哄' : 'Hong','烘' : 'Hong','虹' : 'Hong','鸿' : 'Hong','洪' : 'Hong','宏' : 'Hong','弘' : 'Hong','红' : 'Hong','黉' : 'Hong','訇' : 'Hong','讧' : 'Hong','荭' : 'Hong','蕻' : 'Hong','薨' : 'Hong','闳' : 'Hong','泓' : 'Hong',
'喉' : 'Hou','侯' : 'Hou','猴' : 'Hou','吼' : 'Hou','厚' : 'Hou','候' : 'Hou','后' : 'Hou','堠' : 'Hou','後' : 'Hou','逅' : 'Hou','瘊' : 'Hou','篌' : 'Hou','糇' : 'Hou','鲎' : 'Hou','骺' : 'Hou',
'呼' : 'Hu','乎' : 'Hu','忽' : 'Hu','瑚' : 'Hu','壶' : 'Hu','葫' : 'Hu','胡' : 'Hu','蝴' : 'Hu','狐' : 'Hu','糊' : 'Hu','湖' : 'Hu','弧' : 'Hu','虎' : 'Hu','唬' : 'Hu','护' : 'Hu','互' : 'Hu','沪' : 'Hu','户' : 'Hu','冱' : 'Hu','唿' : 'Hu','囫' : 'Hu','岵' : 'Hu','猢' : 'Hu','怙' : 'Hu','惚' : 'Hu','浒' : 'Hu','滹' : 'Hu','琥' : 'Hu','槲' : 'Hu','轷' : 'Hu','觳' : 'Hu','烀' : 'Hu','煳' : 'Hu','戽' : 'Hu','扈' : 'Hu','祜' : 'Hu','瓠' : 'Hu','鹄' : 'Hu','鹕' : 'Hu','鹱' : 'Hu','笏' : 'Hu','醐' : 'Hu','斛' : 'Hu','鹘' : 'Hu',
'花' : 'Hua','哗' : 'Hua','华' : 'Hua','猾' : 'Hua','滑' : 'Hua','画' : 'Hua','划' : 'Hua','化' : 'Hua','话' : 'Hua','骅' : 'Hua','桦' : 'Hua','砉' : 'Hua','铧' : 'Hua',
'槐' : 'Huai','徊' : 'Huai','怀' : 'Huai','淮' : 'Huai','坏' : 'Huai','踝' : 'Huai',
'欢' : 'Huan','环' : 'Huan','桓' : 'Huan','还' : 'Huan','缓' : 'Huan','换' : 'Huan','患' : 'Huan','唤' : 'Huan','痪' : 'Huan','豢' : 'Huan','焕' : 'Huan','涣' : 'Huan','宦' : 'Huan','幻' : 'Huan','奂' : 'Huan','擐' : 'Huan','圜' : 'Huan','獾' : 'Huan','洹' : 'Huan','浣' : 'Huan','漶' : 'Huan','寰' : 'Huan','逭' : 'Huan','缳' : 'Huan','锾' : 'Huan','鲩' : 'Huan','鬟' : 'Huan',
'荒' : 'Huang','慌' : 'Huang','黄' : 'Huang','磺' : 'Huang','蝗' : 'Huang','簧' : 'Huang','皇' : 'Huang','凰' : 'Huang','惶' : 'Huang','煌' : 'Huang','晃' : 'Huang','幌' : 'Huang','恍' : 'Huang','谎' : 'Huang','隍' : 'Huang','徨' : 'Huang','湟' : 'Huang','潢' : 'Huang','遑' : 'Huang','璜' : 'Huang','肓' : 'Huang','癀' : 'Huang','蟥' : 'Huang','篁' : 'Huang','鳇' : 'Huang',
'灰' : 'Hui','挥' : 'Hui','辉' : 'Hui','徽' : 'Hui','恢' : 'Hui','蛔' : 'Hui','回' : 'Hui','毁' : 'Hui','悔' : 'Hui','慧' : 'Hui','卉' : 'Hui','惠' : 'Hui','晦' : 'Hui','贿' : 'Hui','秽' : 'Hui','会' : 'Hui','烩' : 'Hui','汇' : 'Hui','讳' : 'Hui','诲' : 'Hui','绘' : 'Hui','诙' : 'Hui','茴' : 'Hui','荟' : 'Hui','蕙' : 'Hui','咴' : 'Hui','喙' : 'Hui','隳' : 'Hui','洄' : 'Hui','彗' : 'Hui','缋' : 'Hui','珲' : 'Hui','晖' : 'Hui','恚' : 'Hui','虺' : 'Hui','蟪' : 'Hui','麾' : 'Hui',
'荤' : 'Hun','昏' : 'Hun','婚' : 'Hun','魂' : 'Hun','浑' : 'Hun','混' : 'Hun','诨' : 'Hun','馄' : 'Hun','阍' : 'Hun','溷' : 'Hun',
'豁' : 'Huo','活' : 'Huo','伙' : 'Huo','火' : 'Huo','获' : 'Huo','或' : 'Huo','惑' : 'Huo','霍' : 'Huo','货' : 'Huo','祸' : 'Huo','劐' : 'Huo','藿' : 'Huo','攉' : 'Huo','嚯' : 'Huo','夥' : 'Huo','钬' : 'Huo','锪' : 'Huo','镬' : 'Huo','耠' : 'Huo','蠖' : 'Huo',
'击' : 'Ji','圾' : 'Ji','基' : 'Ji','机' : 'Ji','畸' : 'Ji','稽' : 'Ji','积' : 'Ji','箕' : 'Ji','肌' : 'Ji','饥' : 'Ji','迹' : 'Ji','激' : 'Ji','讥' : 'Ji','鸡' : 'Ji','姬' : 'Ji','绩' : 'Ji','缉' : 'Ji','吉' : 'Ji','极' : 'Ji','棘' : 'Ji','辑' : 'Ji','籍' : 'Ji','集' : 'Ji','及' : 'Ji','急' : 'Ji','疾' : 'Ji','汲' : 'Ji','即' : 'Ji','嫉' : 'Ji','级' : 'Ji','挤' : 'Ji','几' : 'Ji','脊' : 'Ji','己' : 'Ji','蓟' : 'Ji','技' : 'Ji','冀' : 'Ji','季' : 'Ji','伎' : 'Ji','祭' : 'Ji','剂' : 'Ji','悸' : 'Ji','济' : 'Ji','寄' : 'Ji','寂' : 'Ji','计' : 'Ji','记' : 'Ji','既' : 'Ji','忌' : 'Ji','际' : 'Ji','妓' : 'Ji','继' : 'Ji','纪' : 'Ji','藉' : 'Ji','亟' : 'Ji','乩' : 'Ji','剞' : 'Ji','佶' : 'Ji','偈' : 'Ji','墼' : 'Ji','芨' : 'Ji','芰' : 'Ji','荠' : 'Ji','蒺' : 'Ji','蕺' : 'Ji','掎' : 'Ji','叽' : 'Ji','咭' : 'Ji','哜' : 'Ji','唧' : 'Ji','岌' : 'Ji','嵴' : 'Ji','洎' : 'Ji','屐' : 'Ji','骥' : 'Ji','畿' : 'Ji','玑' : 'Ji','楫' : 'Ji','殛' : 'Ji','戟' : 'Ji','戢' : 'Ji','赍' : 'Ji','觊' : 'Ji','犄' : 'Ji','齑' : 'Ji','矶' : 'Ji','羁' : 'Ji','嵇' : 'Ji','稷' : 'Ji','瘠' : 'Ji','虮' : 'Ji','笈' : 'Ji','笄' : 'Ji','暨' : 'Ji','跻' : 'Ji','跽' : 'Ji','霁' : 'Ji','鲚' : 'Ji','鲫' : 'Ji','髻' : 'Ji',
'嘉' : 'Jia','枷' : 'Jia','夹' : 'Jia','佳' : 'Jia','家' : 'Jia','加' : 'Jia','荚' : 'Jia','颊' : 'Jia','贾' : 'Jia','甲' : 'Jia','钾' : 'Jia','假' : 'Jia','稼' : 'Jia','价' : 'Jia','架' : 'Jia','驾' : 'Jia','嫁' : 'Jia','伽' : 'Jia','郏' : 'Jia','葭' : 'Jia','岬' : 'Jia','浃' : 'Jia','迦' : 'Jia','珈' : 'Jia','戛' : 'Jia','胛' : 'Jia','恝' : 'Jia','铗' : 'Jia','镓' : 'Jia','痂' : 'Jia','瘕' : 'Jia','蛱' : 'Jia','笳' : 'Jia','袈' : 'Jia','跏' : 'Jia',
'歼' : 'Jian','监' : 'Jian','坚' : 'Jian','尖' : 'Jian','笺' : 'Jian','间' : 'Jian','煎' : 'Jian','兼' : 'Jian','肩' : 'Jian','艰' : 'Jian','奸' : 'Jian','缄' : 'Jian','茧' : 'Jian','检' : 'Jian','柬' : 'Jian','碱' : 'Jian','硷' : 'Jian','拣' : 'Jian','捡' : 'Jian','简' : 'Jian','俭' : 'Jian','剪' : 'Jian','减' : 'Jian','荐' : 'Jian','槛' : 'Jian','鉴' : 'Jian','践' : 'Jian','贱' : 'Jian','见' : 'Jian','键' : 'Jian','箭' : 'Jian','件' : 'Jian','健' : 'Jian','舰' : 'Jian','剑' : 'Jian','饯' : 'Jian','渐' : 'Jian','溅' : 'Jian','涧' : 'Jian','建' : 'Jian','僭' : 'Jian','谏' : 'Jian','谫' : 'Jian','菅' : 'Jian','蒹' : 'Jian','搛' : 'Jian','湔' : 'Jian','蹇' : 'Jian','謇' : 'Jian','缣' : 'Jian','枧' : 'Jian','楗' : 'Jian','戋' : 'Jian','戬' : 'Jian','牮' : 'Jian','犍' : 'Jian','毽' : 'Jian','腱' : 'Jian','睑' : 'Jian','锏' : 'Jian','鹣' : 'Jian','裥' : 'Jian','笕' : 'Jian','翦' : 'Jian','踺' : 'Jian','鲣' : 'Jian','鞯' : 'Jian',
'僵' : 'Jiang','姜' : 'Jiang','将' : 'Jiang','浆' : 'Jiang','江' : 'Jiang','疆' : 'Jiang','蒋' : 'Jiang','桨' : 'Jiang','奖' : 'Jiang','讲' : 'Jiang','匠' : 'Jiang','酱' : 'Jiang','降' : 'Jiang','茳' : 'Jiang','洚' : 'Jiang','绛' : 'Jiang','缰' : 'Jiang','犟' : 'Jiang','礓' : 'Jiang','耩' : 'Jiang','糨' : 'Jiang','豇' : 'Jiang',
'蕉' : 'Jiao','椒' : 'Jiao','礁' : 'Jiao','焦' : 'Jiao','胶' : 'Jiao','交' : 'Jiao','郊' : 'Jiao','浇' : 'Jiao','骄' : 'Jiao','娇' : 'Jiao','搅' : 'Jiao','铰' : 'Jiao','矫' : 'Jiao','侥' : 'Jiao','脚' : 'Jiao','狡' : 'Jiao','角' : 'Jiao','饺' : 'Jiao','缴' : 'Jiao','绞' : 'Jiao','剿' : 'Jiao','教' : 'Jiao','酵' : 'Jiao','轿' : 'Jiao','较' : 'Jiao','叫' : 'Jiao','窖' : 'Jiao','佼' : 'Jiao','僬' : 'Jiao','艽' : 'Jiao','茭' : 'Jiao','挢' : 'Jiao','噍' : 'Jiao','峤' : 'Jiao','徼' : 'Jiao','姣' : 'Jiao','敫' : 'Jiao','皎' : 'Jiao','鹪' : 'Jiao','蛟' : 'Jiao','醮' : 'Jiao','跤' : 'Jiao','鲛' : 'Jiao',
'嚼' : 'Jue','撅' : 'Jue','攫' : 'Jue','抉' : 'Jue','掘' : 'Jue','倔' : 'Jue','爵' : 'Jue','觉' : 'Jue','决' : 'Jue','诀' : 'Jue','绝' : 'Jue','厥' : 'Jue','劂' : 'Jue','谲' : 'Jue','矍' : 'Jue','蕨' : 'Jue','噘' : 'Jue','崛' : 'Jue','獗' : 'Jue','孓' : 'Jue','珏' : 'Jue','桷' : 'Jue','橛' : 'Jue','爝' : 'Jue','镢' : 'Jue','蹶' : 'Jue','觖' : 'Jue',
'揭' : 'Jie','接' : 'Jie','皆' : 'Jie','秸' : 'Jie','街' : 'Jie','阶' : 'Jie','截' : 'Jie','劫' : 'Jie','节' : 'Jie','桔' : 'Jie','杰' : 'Jie','捷' : 'Jie','睫' : 'Jie','竭' : 'Jie','洁' : 'Jie','结' : 'Jie','解' : 'Jie','姐' : 'Jie','戒' : 'Jie','芥' : 'Jie','界' : 'Jie','借' : 'Jie','介' : 'Jie','疥' : 'Jie','诫' : 'Jie','届' : 'Jie','讦' : 'Jie','诘' : 'Jie','拮' : 'Jie','喈' : 'Jie','嗟' : 'Jie','婕' : 'Jie','孑' : 'Jie','桀' : 'Jie','碣' : 'Jie','疖' : 'Jie','颉' : 'Jie','蚧' : 'Jie','羯' : 'Jie','鲒' : 'Jie','骱' : 'Jie',
'巾' : 'Jin','筋' : 'Jin','斤' : 'Jin','金' : 'Jin','今' : 'Jin','津' : 'Jin','襟' : 'Jin','紧' : 'Jin','锦' : 'Jin','仅' : 'Jin','谨' : 'Jin','进' : 'Jin','靳' : 'Jin','晋' : 'Jin','禁' : 'Jin','近' : 'Jin','烬' : 'Jin','浸' : 'Jin','尽' : 'Jin','劲' : 'Jin','卺' : 'Jin','荩' : 'Jin','堇' : 'Jin','噤' : 'Jin','馑' : 'Jin','廑' : 'Jin','妗' : 'Jin','缙' : 'Jin','瑾' : 'Jin','槿' : 'Jin','赆' : 'Jin','觐' : 'Jin','衿' : 'Jin','矜' : 'Jin',
'荆' : 'Jing','兢' : 'Jing','茎' : 'Jing','睛' : 'Jing','晶' : 'Jing','鲸' : 'Jing','京' : 'Jing','惊' : 'Jing','精' : 'Jing','粳' : 'Jing','经' : 'Jing','井' : 'Jing','警' : 'Jing','景' : 'Jing','颈' : 'Jing','静' : 'Jing','境' : 'Jing','敬' : 'Jing','镜' : 'Jing','径' : 'Jing','痉' : 'Jing','靖' : 'Jing','竟' : 'Jing','竞' : 'Jing','净' : 'Jing','刭' : 'Jing','儆' : 'Jing','阱' : 'Jing','菁' : 'Jing','獍' : 'Jing','憬' : 'Jing','泾' : 'Jing','迳' : 'Jing','弪' : 'Jing','婧' : 'Jing','肼' : 'Jing','胫' : 'Jing','腈' : 'Jing','旌' : 'Jing','箐' : 'Jing',
'炯' : 'Jiong','窘' : 'Jiong','迥' : 'Jiong','扃' : 'Jiong',
'揪' : 'Jiu','究' : 'Jiu','纠' : 'Jiu','玖' : 'Jiu','韭' : 'Jiu','久' : 'Jiu','灸' : 'Jiu','九' : 'Jiu','酒' : 'Jiu','厩' : 'Jiu','救' : 'Jiu','旧' : 'Jiu','臼' : 'Jiu','舅' : 'Jiu','咎' : 'Jiu','就' : 'Jiu','疚' : 'Jiu','僦' : 'Jiu','啾' : 'Jiu','阄' : 'Jiu','柩' : 'Jiu','桕' : 'Jiu','鸠' : 'Jiu','鹫' : 'Jiu','赳' : 'Jiu','鬏' : 'Jiu',
'鞠' : 'Ju','拘' : 'Ju','狙' : 'Ju','疽' : 'Ju','居' : 'Ju','驹' : 'Ju','菊' : 'Ju','局' : 'Ju','咀' : 'Ju','矩' : 'Ju','举' : 'Ju','沮' : 'Ju','聚' : 'Ju','拒' : 'Ju','据' : 'Ju','巨' : 'Ju','具' : 'Ju','距' : 'Ju','踞' : 'Ju','锯' : 'Ju','俱' : 'Ju','句' : 'Ju','惧' : 'Ju','炬' : 'Ju','剧' : 'Ju','倨' : 'Ju','讵' : 'Ju','苣' : 'Ju','苴' : 'Ju','莒' : 'Ju','掬' : 'Ju','遽' : 'Ju','屦' : 'Ju','琚' : 'Ju','椐' : 'Ju','榘' : 'Ju','榉' : 'Ju','橘' : 'Ju','犋' : 'Ju','飓' : 'Ju','钜' : 'Ju','锔' : 'Ju','窭' : 'Ju','裾' : 'Ju','醵' : 'Ju','踽' : 'Ju','龃' : 'Ju','雎' : 'Ju','鞫' : 'Ju',
'捐' : 'Juan','鹃' : 'Juan','娟' : 'Juan','倦' : 'Juan','眷' : 'Juan','卷' : 'Juan','绢' : 'Juan','鄄' : 'Juan','狷' : 'Juan','涓' : 'Juan','桊' : 'Juan','蠲' : 'Juan','锩' : 'Juan','镌' : 'Juan','隽' : 'Juan',
'均' : 'Jun','菌' : 'Jun','钧' : 'Jun','军' : 'Jun','君' : 'Jun','峻' : 'Jun','俊' : 'Jun','竣' : 'Jun','浚' : 'Jun','郡' : 'Jun','骏' : 'Jun','捃' : 'Jun','皲' : 'Jun','筠' : 'Jun','麇' : 'Jun',
'喀' : 'Ka','咖' : 'Ka','卡' : 'Ka','佧' : 'Ka','咔' : 'Ka','胩' : 'Ka',
'咯' : 'Luo','萝' : 'Luo','螺' : 'Luo','罗' : 'Luo','逻' : 'Luo','锣' : 'Luo','箩' : 'Luo','骡' : 'Luo','裸' : 'Luo','落' : 'Luo','洛' : 'Luo','骆' : 'Luo','络' : 'Luo','倮' : 'Luo','蠃' : 'Luo','荦' : 'Luo','摞' : 'Luo','猡' : 'Luo','泺' : 'Luo','漯' : 'Luo','珞' : 'Luo','椤' : 'Luo','脶' : 'Luo','镙' : 'Luo','瘰' : 'Luo','雒' : 'Luo',
'开' : 'Kai','揩' : 'Kai','楷' : 'Kai','凯' : 'Kai','慨' : 'Kai','剀' : 'Kai','垲' : 'Kai','蒈' : 'Kai','忾' : 'Kai','恺' : 'Kai','铠' : 'Kai','锎' : 'Kai','锴' : 'Kai',
'刊' : 'Kan','堪' : 'Kan','勘' : 'Kan','坎' : 'Kan','砍' : 'Kan','看' : 'Kan','侃' : 'Kan','莰' : 'Kan','阚' : 'Kan','戡' : 'Kan','龛' : 'Kan','瞰' : 'Kan',
'康' : 'Kang','慷' : 'Kang','糠' : 'Kang','扛' : 'Kang','抗' : 'Kang','亢' : 'Kang','炕' : 'Kang','伉' : 'Kang','闶' : 'Kang','钪' : 'Kang',
'考' : 'Kao','拷' : 'Kao','烤' : 'Kao','靠' : 'Kao','尻' : 'Kao','栲' : 'Kao','犒' : 'Kao','铐' : 'Kao',
'坷' : 'Ke','苛' : 'Ke','柯' : 'Ke','棵' : 'Ke','磕' : 'Ke','颗' : 'Ke','科' : 'Ke','壳' : 'Ke','咳' : 'Ke','可' : 'Ke','渴' : 'Ke','克' : 'Ke','刻' : 'Ke','客' : 'Ke','课' : 'Ke','嗑' : 'Ke','岢' : 'Ke','恪' : 'Ke','溘' : 'Ke','骒' : 'Ke','缂' : 'Ke','珂' : 'Ke','轲' : 'Ke','氪' : 'Ke','瞌' : 'Ke','钶' : 'Ke','锞' : 'Ke','稞' : 'Ke','疴' : 'Ke','窠' : 'Ke','颏' : 'Ke','蝌' : 'Ke','髁' : 'Ke',
'肯' : 'Ken','啃' : 'Ken','垦' : 'Ken','恳' : 'Ken','裉' : 'Ken',
'坑' : 'Keng','吭' : 'Keng','铿' : 'Keng',
'空' : 'Kong','恐' : 'Kong','孔' : 'Kong','控' : 'Kong','倥' : 'Kong','崆' : 'Kong','箜' : 'Kong',
'抠' : 'Kou','口' : 'Kou','扣' : 'Kou','寇' : 'Kou','芤' : 'Kou','蔻' : 'Kou','叩' : 'Kou','囗' : 'Kou','眍' : 'Kou','筘' : 'Kou',
'枯' : 'Ku','哭' : 'Ku','窟' : 'Ku','苦' : 'Ku','酷' : 'Ku','库' : 'Ku','裤' : 'Ku','刳' : 'Ku','堀' : 'Ku','喾' : 'Ku','绔' : 'Ku','骷' : 'Ku',
'夸' : 'Kua','垮' : 'Kua','挎' : 'Kua','跨' : 'Kua','胯' : 'Kua','侉' : 'Kua',
'块' : 'Kuai','筷' : 'Kuai','侩' : 'Kuai','快' : 'Kuai','蒯' : 'Kuai','郐' : 'Kuai','哙' : 'Kuai','狯' : 'Kuai','浍' : 'Kuai','脍' : 'Kuai',
'宽' : 'Kuan','款' : 'Kuan','髋' : 'Kuan',
'匡' : 'Kuang','筐' : 'Kuang','狂' : 'Kuang','框' : 'Kuang','矿' : 'Kuang','眶' : 'Kuang','旷' : 'Kuang','况' : 'Kuang','诓' : 'Kuang','诳' : 'Kuang','邝' : 'Kuang','圹' : 'Kuang','夼' : 'Kuang','哐' : 'Kuang','纩' : 'Kuang','贶' : 'Kuang',
'亏' : 'Kui','盔' : 'Kui','岿' : 'Kui','窥' : 'Kui','葵' : 'Kui','奎' : 'Kui','魁' : 'Kui','傀' : 'Kui','馈' : 'Kui','愧' : 'Kui','溃' : 'Kui','馗' : 'Kui','匮' : 'Kui','夔' : 'Kui','隗' : 'Kui','蒉' : 'Kui','揆' : 'Kui','喹' : 'Kui','喟' : 'Kui','悝' : 'Kui','愦' : 'Kui','逵' : 'Kui','暌' : 'Kui','睽' : 'Kui','聩' : 'Kui','蝰' : 'Kui','篑' : 'Kui','跬' : 'Kui',
'坤' : 'Kun','昆' : 'Kun','捆' : 'Kun','困' : 'Kun','悃' : 'Kun','阃' : 'Kun','琨' : 'Kun','锟' : 'Kun','醌' : 'Kun','鲲' : 'Kun','髡' : 'Kun',
'括' : 'Kuo','扩' : 'Kuo','廓' : 'Kuo','阔' : 'Kuo','蛞' : 'Kuo',
'垃' : 'La','拉' : 'La','喇' : 'La','蜡' : 'La','腊' : 'La','辣' : 'La','啦' : 'La','剌' : 'La','邋' : 'La','旯' : 'La','砬' : 'La','瘌' : 'La',
'莱' : 'Lai','来' : 'Lai','赖' : 'Lai','崃' : 'Lai','徕' : 'Lai','涞' : 'Lai','濑' : 'Lai','赉' : 'Lai','睐' : 'Lai','铼' : 'Lai','癞' : 'Lai','籁' : 'Lai',
'蓝' : 'Lan','婪' : 'Lan','栏' : 'Lan','拦' : 'Lan','篮' : 'Lan','阑' : 'Lan','兰' : 'Lan','澜' : 'Lan','谰' : 'Lan','揽' : 'Lan','览' : 'Lan','懒' : 'Lan','缆' : 'Lan','烂' : 'Lan','滥' : 'Lan','岚' : 'Lan','漤' : 'Lan','榄' : 'Lan','斓' : 'Lan','罱' : 'Lan','镧' : 'Lan','褴' : 'Lan',
'琅' : 'Lang','榔' : 'Lang','狼' : 'Lang','廊' : 'Lang','郎' : 'Lang','朗' : 'Lang','浪' : 'Lang','蒗' : 'Lang','啷' : 'Lang','阆' : 'Lang','稂' : 'Lang','螂' : 'Lang',
'捞' : 'Lao','劳' : 'Lao','牢' : 'Lao','老' : 'Lao','佬' : 'Lao','姥' : 'Lao','酪' : 'Lao','烙' : 'Lao','涝' : 'Lao','唠' : 'Lao','崂' : 'Lao','忉' : 'Lao','栳' : 'Lao','铑' : 'Lao','铹' : 'Lao','痨' : 'Lao','耢' : 'Lao','醪' : 'Lao',
'勒' : 'Le','了' : 'Le','仂' : 'Le','叻' : 'Le','泐' : 'Le','鳓' : 'Le',
'乐' : 'Yue','曰' : 'Yue','约' : 'Yue','越' : 'Yue','跃' : 'Yue','岳' : 'Yue','粤' : 'Yue','月' : 'Yue','悦' : 'Yue','阅' : 'Yue','龠' : 'Yue','哕' : 'Yue','瀹' : 'Yue','樾' : 'Yue','刖' : 'Yue','钺' : 'Yue',
'雷' : 'Lei','镭' : 'Lei','蕾' : 'Lei','磊' : 'Lei','累' : 'Lei','儡' : 'Lei','垒' : 'Lei','擂' : 'Lei','肋' : 'Lei','类' : 'Lei','泪' : 'Lei','羸' : 'Lei','诔' : 'Lei','嘞' : 'Lei','嫘' : 'Lei','缧' : 'Lei','檑' : 'Lei','耒' : 'Lei','酹' : 'Lei',
'棱' : 'Leng','楞' : 'Leng','冷' : 'Leng','塄' : 'Leng','愣' : 'Leng',
'厘' : 'Li','梨' : 'Li','犁' : 'Li','黎' : 'Li','篱' : 'Li','狸' : 'Li','离' : 'Li','漓' : 'Li','理' : 'Li','李' : 'Li','里' : 'Li','鲤' : 'Li','礼' : 'Li','莉' : 'Li','荔' : 'Li','吏' : 'Li','栗' : 'Li','丽' : 'Li','厉' : 'Li','励' : 'Li','砾' : 'Li','历' : 'Li','利' : 'Li','傈' : 'Li','例' : 'Li','俐' : 'Li','痢' : 'Li','立' : 'Li','粒' : 'Li','沥' : 'Li','隶' : 'Li','力' : 'Li','璃' : 'Li','哩' : 'Li','俪' : 'Li','俚' : 'Li','郦' : 'Li','坜' : 'Li','苈' : 'Li','莅' : 'Li','蓠' : 'Li','藜' : 'Li','呖' : 'Li','唳' : 'Li','喱' : 'Li','猁' : 'Li','溧' : 'Li','澧' : 'Li','逦' : 'Li','娌' : 'Li','嫠' : 'Li','骊' : 'Li','缡' : 'Li','枥' : 'Li','栎' : 'Li','轹' : 'Li','膦' : 'Li','戾' : 'Li','砺' : 'Li','詈' : 'Li','罹' : 'Li','锂' : 'Li','鹂' : 'Li','疠' : 'Li','疬' : 'Li','蛎' : 'Li','蜊' : 'Li','蠡' : 'Li','笠' : 'Li','篥' : 'Li','粝' : 'Li','醴' : 'Li','跞' : 'Li','雳' : 'Li','鲡' : 'Li','鳢' : 'Li','黧' : 'Li',
'俩' : 'Lia',
'联' : 'Lian','莲' : 'Lian','连' : 'Lian','镰' : 'Lian','廉' : 'Lian','怜' : 'Lian','涟' : 'Lian','帘' : 'Lian','敛' : 'Lian','脸' : 'Lian','链' : 'Lian','恋' : 'Lian','炼' : 'Lian','练' : 'Lian','蔹' : 'Lian','奁' : 'Lian','潋' : 'Lian','濂' : 'Lian','琏' : 'Lian','楝' : 'Lian','殓' : 'Lian','臁' : 'Lian','裢' : 'Lian','裣' : 'Lian','蠊' : 'Lian','鲢' : 'Lian',
'粮' : 'Liang','凉' : 'Liang','梁' : 'Liang','粱' : 'Liang','良' : 'Liang','两' : 'Liang','辆' : 'Liang','量' : 'Liang','晾' : 'Liang','亮' : 'Liang','谅' : 'Liang','墚' : 'Liang','莨' : 'Liang','椋' : 'Liang','锒' : 'Liang','踉' : 'Liang','靓' : 'Liang','魉' : 'Liang',
'撩' : 'Liao','聊' : 'Liao','僚' : 'Liao','疗' : 'Liao','燎' : 'Liao','寥' : 'Liao','辽' : 'Liao','潦' : 'Liao','撂' : 'Liao','镣' : 'Liao','廖' : 'Liao','料' : 'Liao','蓼' : 'Liao','尥' : 'Liao','嘹' : 'Liao','獠' : 'Liao','寮' : 'Liao','缭' : 'Liao','钌' : 'Liao','鹩' : 'Liao',
'列' : 'Lie','裂' : 'Lie','烈' : 'Lie','劣' : 'Lie','猎' : 'Lie','冽' : 'Lie','埒' : 'Lie','捩' : 'Lie','咧' : 'Lie','洌' : 'Lie','趔' : 'Lie','躐' : 'Lie','鬣' : 'Lie',
'琳' : 'Lin','林' : 'Lin','磷' : 'Lin','霖' : 'Lin','临' : 'Lin','邻' : 'Lin','鳞' : 'Lin','淋' : 'Lin','凛' : 'Lin','赁' : 'Lin','吝' : 'Lin','拎' : 'Lin','蔺' : 'Lin','啉' : 'Lin','嶙' : 'Lin','廪' : 'Lin','懔' : 'Lin','遴' : 'Lin','檩' : 'Lin','辚' : 'Lin','瞵' : 'Lin','粼' : 'Lin','躏' : 'Lin','麟' : 'Lin',
'玲' : 'Ling','菱' : 'Ling','零' : 'Ling','龄' : 'Ling','铃' : 'Ling','伶' : 'Ling','羚' : 'Ling','凌' : 'Ling','灵' : 'Ling','陵' : 'Ling','岭' : 'Ling','领' : 'Ling','另' : 'Ling','令' : 'Ling','酃' : 'Ling','苓' : 'Ling','呤' : 'Ling','囹' : 'Ling','泠' : 'Ling','绫' : 'Ling','柃' : 'Ling','棂' : 'Ling','瓴' : 'Ling','聆' : 'Ling','蛉' : 'Ling','翎' : 'Ling','鲮' : 'Ling',
'溜' : 'Liu','琉' : 'Liu','榴' : 'Liu','硫' : 'Liu','馏' : 'Liu','留' : 'Liu','刘' : 'Liu','瘤' : 'Liu','流' : 'Liu','柳' : 'Liu','六' : 'Liu','浏' : 'Liu','遛' : 'Liu','骝' : 'Liu','绺' : 'Liu','旒' : 'Liu','熘' : 'Liu','锍' : 'Liu','镏' : 'Liu','鹨' : 'Liu','鎏' : 'Liu',
'龙' : 'Long','聋' : 'Long','咙' : 'Long','笼' : 'Long','窿' : 'Long','隆' : 'Long','垄' : 'Long','拢' : 'Long','陇' : 'Long','垅' : 'Long','茏' : 'Long','珑' : 'Long','栊' : 'Long','胧' : 'Long','砻' : 'Long','癃' : 'Long',
'楼' : 'Lou','娄' : 'Lou','搂' : 'Lou','篓' : 'Lou','漏' : 'Lou','陋' : 'Lou','偻' : 'Lou','蒌' : 'Lou','喽' : 'Lou','嵝' : 'Lou','镂' : 'Lou','瘘' : 'Lou','耧' : 'Lou','蝼' : 'Lou','髅' : 'Lou',
'芦' : 'Lu','卢' : 'Lu','颅' : 'Lu','庐' : 'Lu','炉' : 'Lu','掳' : 'Lu','卤' : 'Lu','虏' : 'Lu','鲁' : 'Lu','麓' : 'Lu','碌' : 'Lu','露' : 'Lu','路' : 'Lu','赂' : 'Lu','鹿' : 'Lu','潞' : 'Lu','禄' : 'Lu','录' : 'Lu','陆' : 'Lu','戮' : 'Lu','垆' : 'Lu','撸' : 'Lu','噜' : 'Lu','泸' : 'Lu','渌' : 'Lu','漉' : 'Lu','逯' : 'Lu','璐' : 'Lu','栌' : 'Lu','橹' : 'Lu','轳' : 'Lu','辂' : 'Lu','辘' : 'Lu','氇' : 'Lu','胪' : 'Lu','镥' : 'Lu','鸬' : 'Lu','鹭' : 'Lu','簏' : 'Lu','舻' : 'Lu','鲈' : 'Lu',
'驴' : 'Lv','吕' : 'Lv','铝' : 'Lv','侣' : 'Lv','旅' : 'Lv','履' : 'Lv','屡' : 'Lv','缕' : 'Lv','虑' : 'Lv','氯' : 'Lv','律' : 'Lv','率' : 'Lv','滤' : 'Lv','绿' : 'Lv','捋' : 'Lv','闾' : 'Lv','榈' : 'Lv','膂' : 'Lv','稆' : 'Lv','褛' : 'Lv',
'峦' : 'Luan','挛' : 'Luan','孪' : 'Luan','滦' : 'Luan','卵' : 'Luan','乱' : 'Luan','脔' : 'Luan','娈' : 'Luan','栾' : 'Luan','鸾' : 'Luan','銮' : 'Luan',
'掠' : 'Lue','略' : 'Lue','锊' : 'Lue',
'抡' : 'Lun','轮' : 'Lun','伦' : 'Lun','仑' : 'Lun','沦' : 'Lun','纶' : 'Lun','论' : 'Lun','囵' : 'Lun',
'妈' : 'Ma','麻' : 'Ma','玛' : 'Ma','码' : 'Ma','蚂' : 'Ma','马' : 'Ma','骂' : 'Ma','嘛' : 'Ma','吗' : 'Ma','唛' : 'Ma','犸' : 'Ma','杩' : 'Ma','蟆' : 'Ma',
'埋' : 'Mai','买' : 'Mai','麦' : 'Mai','卖' : 'Mai','迈' : 'Mai','脉' : 'Mai','劢' : 'Mai','荬' : 'Mai','霾' : 'Mai',
'瞒' : 'Man','馒' : 'Man','蛮' : 'Man','满' : 'Man','蔓' : 'Man','曼' : 'Man','慢' : 'Man','漫' : 'Man','谩' : 'Man','墁' : 'Man','幔' : 'Man','缦' : 'Man','熳' : 'Man','镘' : 'Man','颟' : 'Man','螨' : 'Man','鳗' : 'Man','鞔' : 'Man',
'芒' : 'Mang','茫' : 'Mang','盲' : 'Mang','氓' : 'Mang','忙' : 'Mang','莽' : 'Mang','邙' : 'Mang','漭' : 'Mang','硭' : 'Mang','蟒' : 'Mang',
'猫' : 'Mao','茅' : 'Mao','锚' : 'Mao','毛' : 'Mao','矛' : 'Mao','铆' : 'Mao','卯' : 'Mao','茂' : 'Mao','冒' : 'Mao','帽' : 'Mao','貌' : 'Mao','贸' : 'Mao','袤' : 'Mao','茆' : 'Mao','峁' : 'Mao','泖' : 'Mao','瑁' : 'Mao','昴' : 'Mao','牦' : 'Mao','耄' : 'Mao','旄' : 'Mao','懋' : 'Mao','瞀' : 'Mao','蝥' : 'Mao','蟊' : 'Mao','髦' : 'Mao',
'么' : 'Me','麽' : 'Me',
'玫' : 'Mei','枚' : 'Mei','梅' : 'Mei','酶' : 'Mei','霉' : 'Mei','煤' : 'Mei','眉' : 'Mei','媒' : 'Mei','镁' : 'Mei','每' : 'Mei','美' : 'Mei','昧' : 'Mei','寐' : 'Mei','妹' : 'Mei','媚' : 'Mei','莓' : 'Mei','嵋' : 'Mei','猸' : 'Mei','浼' : 'Mei','湄' : 'Mei','楣' : 'Mei','镅' : 'Mei','鹛' : 'Mei','袂' : 'Mei','魅' : 'Mei',
'没' : 'Mo','摸' : 'Mo','摹' : 'Mo','蘑' : 'Mo','模' : 'Mo','膜' : 'Mo','磨' : 'Mo','摩' : 'Mo','魔' : 'Mo','抹' : 'Mo','末' : 'Mo','莫' : 'Mo','墨' : 'Mo','默' : 'Mo','沫' : 'Mo','漠' : 'Mo','寞' : 'Mo','陌' : 'Mo','谟' : 'Mo','茉' : 'Mo','蓦' : 'Mo','馍' : 'Mo','嫫' : 'Mo','嬷' : 'Mo','殁' : 'Mo','镆' : 'Mo','秣' : 'Mo','瘼' : 'Mo','耱' : 'Mo','貊' : 'Mo','貘' : 'Mo',
'门' : 'Men','闷' : 'Men','们' : 'Men','扪' : 'Men','焖' : 'Men','懑' : 'Men','钔' : 'Men',
'萌' : 'Meng','蒙' : 'Meng','檬' : 'Meng','盟' : 'Meng','锰' : 'Meng','猛' : 'Meng','梦' : 'Meng','孟' : 'Meng','勐' : 'Meng','甍' : 'Meng','瞢' : 'Meng','懵' : 'Meng','朦' : 'Meng','礞' : 'Meng','虻' : 'Meng','蜢' : 'Meng','蠓' : 'Meng','艋' : 'Meng','艨' : 'Meng',
'眯' : 'Mi','醚' : 'Mi','靡' : 'Mi','糜' : 'Mi','迷' : 'Mi','谜' : 'Mi','弥' : 'Mi','米' : 'Mi','秘' : 'Mi','觅' : 'Mi','泌' : 'Mi','蜜' : 'Mi','密' : 'Mi','幂' : 'Mi','芈' : 'Mi','谧' : 'Mi','咪' : 'Mi','嘧' : 'Mi','猕' : 'Mi','汨' : 'Mi','宓' : 'Mi','弭' : 'Mi','脒' : 'Mi','祢' : 'Mi','敉' : 'Mi','縻' : 'Mi','麋' : 'Mi',
'棉' : 'Mian','眠' : 'Mian','绵' : 'Mian','冕' : 'Mian','免' : 'Mian','勉' : 'Mian','娩' : 'Mian','缅' : 'Mian','面' : 'Mian','沔' : 'Mian','渑' : 'Mian','湎' : 'Mian','腼' : 'Mian','眄' : 'Mian',
'苗' : 'Miao','描' : 'Miao','瞄' : 'Miao','藐' : 'Miao','秒' : 'Miao','渺' : 'Miao','庙' : 'Miao','妙' : 'Miao','喵' : 'Miao','邈' : 'Miao','缈' : 'Miao','杪' : 'Miao','淼' : 'Miao','眇' : 'Miao','鹋' : 'Miao',
'蔑' : 'Mie','灭' : 'Mie','乜' : 'Mie','咩' : 'Mie','蠛' : 'Mie','篾' : 'Mie',
'民' : 'Min','抿' : 'Min','皿' : 'Min','敏' : 'Min','悯' : 'Min','闽' : 'Min','苠' : 'Min','岷' : 'Min','闵' : 'Min','泯' : 'Min','缗' : 'Min','玟' : 'Min','珉' : 'Min','愍' : 'Min','黾' : 'Min','鳘' : 'Min',
'明' : 'Ming','螟' : 'Ming','鸣' : 'Ming','铭' : 'Ming','名' : 'Ming','命' : 'Ming','冥' : 'Ming','茗' : 'Ming','溟' : 'Ming','暝' : 'Ming','瞑' : 'Ming','酩' : 'Ming',
'谬' : 'Miu','缪' : 'Miu',
'谋' : 'Mou','牟' : 'Mou','某' : 'Mou','侔' : 'Mou','哞' : 'Mou','眸' : 'Mou','蛑' : 'Mou','鍪' : 'Mou',
'拇' : 'Mu','牡' : 'Mu','亩' : 'Mu','姆' : 'Mu','母' : 'Mu','墓' : 'Mu','暮' : 'Mu','幕' : 'Mu','募' : 'Mu','慕' : 'Mu','木' : 'Mu','目' : 'Mu','睦' : 'Mu','牧' : 'Mu','穆' : 'Mu','仫' : 'Mu','坶' : 'Mu','苜' : 'Mu','沐' : 'Mu','毪' : 'Mu','钼' : 'Mu',
'拿' : 'Na','哪' : 'Na','呐' : 'Na','钠' : 'Na','那' : 'Na','娜' : 'Na','纳' : 'Na','讷' : 'Na','捺' : 'Na','肭' : 'Na','镎' : 'Na','衲' : 'Na',
'氖' : 'Nai','乃' : 'Nai','奶' : 'Nai','耐' : 'Nai','奈' : 'Nai','鼐' : 'Nai','佴' : 'Nai','艿' : 'Nai','萘' : 'Nai','柰' : 'Nai',
'南' : 'Nan','男' : 'Nan','难' : 'Nan','喃' : 'Nan','囝' : 'Nan','囡' : 'Nan','楠' : 'Nan','腩' : 'Nan','蝻' : 'Nan','赧' : 'Nan',
'囊' : 'Nang','攮' : 'Nang','囔' : 'Nang','馕' : 'Nang','曩' : 'Nang',
'挠' : 'Nao','脑' : 'Nao','恼' : 'Nao','闹' : 'Nao','淖' : 'Nao','孬' : 'Nao','垴' : 'Nao','呶' : 'Nao','猱' : 'Nao','瑙' : 'Nao','硇' : 'Nao','铙' : 'Nao','蛲' : 'Nao',
'呢' : 'Ne',
'馁' : 'Nei','内' : 'Nei',
'嫩' : 'Nen','恁' : 'Nen',
'能' : 'Neng',
'妮' : 'Ni','霓' : 'Ni','倪' : 'Ni','泥' : 'Ni','尼' : 'Ni','拟' : 'Ni','你' : 'Ni','匿' : 'Ni','腻' : 'Ni','逆' : 'Ni','溺' : 'Ni','伲' : 'Ni','坭' : 'Ni','蘼' : 'Ni','猊' : 'Ni','怩' : 'Ni','昵' : 'Ni','旎' : 'Ni','睨' : 'Ni','铌' : 'Ni','鲵' : 'Ni',
'蔫' : 'Nian','拈' : 'Nian','年' : 'Nian','碾' : 'Nian','撵' : 'Nian','捻' : 'Nian','念' : 'Nian','廿' : 'Nian','埝' : 'Nian','辇' : 'Nian','黏' : 'Nian','鲇' : 'Nian','鲶' : 'Nian',
'娘' : 'Niang','酿' : 'Niang',
'鸟' : 'Niao','尿' : 'Niao','茑' : 'Niao','嬲' : 'Niao','脲' : 'Niao','袅' : 'Niao',
'捏' : 'Nie','聂' : 'Nie','孽' : 'Nie','啮' : 'Nie','镊' : 'Nie','镍' : 'Nie','涅' : 'Nie','陧' : 'Nie','蘖' : 'Nie','嗫' : 'Nie','颞' : 'Nie','臬' : 'Nie','蹑' : 'Nie',
'您' : 'Nin',
'柠' : 'Ning','狞' : 'Ning','凝' : 'Ning','宁' : 'Ning','拧' : 'Ning','泞' : 'Ning','佞' : 'Ning','咛' : 'Ning','甯' : 'Ning','聍' : 'Ning',
'牛' : 'Niu','扭' : 'Niu','钮' : 'Niu','纽' : 'Niu','拗' : 'Niu','狃' : 'Niu','忸' : 'Niu','妞' : 'Niu',
'脓' : 'Nong','浓' : 'Nong','农' : 'Nong','弄' : 'Nong','侬' : 'Nong','哝' : 'Nong',
'奴' : 'Nu','努' : 'Nu','怒' : 'Nu','弩' : 'Nu','胬' : 'Nu','孥' : 'Nu','驽' : 'Nu',
'女' : 'Nv','恧' : 'Nv','钕' : 'Nv','衄' : 'Nv',
'暖' : 'Nuan',
'虐' : 'Nue','疟' : 'Nue','挪' : 'Nue',
'懦' : 'Nuo','糯' : 'Nuo','诺' : 'Nuo','傩' : 'Nuo','搦' : 'Nuo','喏' : 'Nuo','锘' : 'Nuo',
'哦' : 'O','噢' : 'O',
'欧' : 'Ou','鸥' : 'Ou','殴' : 'Ou','藕' : 'Ou','呕' : 'Ou','偶' : 'Ou','沤' : 'Ou','讴' : 'Ou','怄' : 'Ou','瓯' : 'Ou','耦' : 'Ou',
'啪' : 'Pa','趴' : 'Pa','爬' : 'Pa','帕' : 'Pa','怕' : 'Pa','琶' : 'Pa','葩' : 'Pa','杷' : 'Pa','筢' : 'Pa',
'拍' : 'Pai','排' : 'Pai','牌' : 'Pai','徘' : 'Pai','湃' : 'Pai','派' : 'Pai','俳' : 'Pai','蒎' : 'Pai','哌' : 'Pai',
'攀' : 'Pan','潘' : 'Pan','盘' : 'Pan','磐' : 'Pan','盼' : 'Pan','畔' : 'Pan','判' : 'Pan','叛' : 'Pan','拚' : 'Pan','爿' : 'Pan','泮' : 'Pan','袢' : 'Pan','襻' : 'Pan','蟠' : 'Pan','蹒' : 'Pan',
'乓' : 'Pang','庞' : 'Pang','旁' : 'Pang','耪' : 'Pang','胖' : 'Pang','彷' : 'Pang','滂' : 'Pang','逄' : 'Pang','螃' : 'Pang',
'抛' : 'Pao','咆' : 'Pao','刨' : 'Pao','炮' : 'Pao','袍' : 'Pao','跑' : 'Pao','泡' : 'Pao','匏' : 'Pao','狍' : 'Pao','庖' : 'Pao','脬' : 'Pao','疱' : 'Pao',
'呸' : 'Pei','胚' : 'Pei','培' : 'Pei','裴' : 'Pei','赔' : 'Pei','陪' : 'Pei','配' : 'Pei','佩' : 'Pei','沛' : 'Pei','辔' : 'Pei','帔' : 'Pei','旆' : 'Pei','锫' : 'Pei','醅' : 'Pei','霈' : 'Pei',
'喷' : 'Pen','盆' : 'Pen','湓' : 'Pen',
'砰' : 'Peng','抨' : 'Peng','烹' : 'Peng','澎' : 'Peng','彭' : 'Peng','蓬' : 'Peng','棚' : 'Peng','硼' : 'Peng','篷' : 'Peng','膨' : 'Peng','朋' : 'Peng','鹏' : 'Peng','捧' : 'Peng','碰' : 'Peng','堋' : 'Peng','嘭' : 'Peng','怦' : 'Peng','蟛' : 'Peng',
'篇' : 'Pian','偏' : 'Pian','片' : 'Pian','骗' : 'Pian','谝' : 'Pian','骈' : 'Pian','犏' : 'Pian','胼' : 'Pian','翩' : 'Pian','蹁' : 'Pian',
'飘' : 'Piao','漂' : 'Piao','瓢' : 'Piao','票' : 'Piao','剽' : 'Piao','嘌' : 'Piao','嫖' : 'Piao','缥' : 'Piao','殍' : 'Piao','瞟' : 'Piao','螵' : 'Piao',
'撇' : 'Pie','瞥' : 'Pie','丿' : 'Pie','苤' : 'Pie','氕' : 'Pie',
'拼' : 'Pin','频' : 'Pin','贫' : 'Pin','品' : 'Pin','聘' : 'Pin','姘' : 'Pin','嫔' : 'Pin','榀' : 'Pin','牝' : 'Pin','颦' : 'Pin',
'乒' : 'Ping','坪' : 'Ping','苹' : 'Ping','萍' : 'Ping','平' : 'Ping','凭' : 'Ping','瓶' : 'Ping','评' : 'Ping','屏' : 'Ping','俜' : 'Ping','娉' : 'Ping','枰' : 'Ping','鲆' : 'Ping',
'坡' : 'Po','泼' : 'Po','颇' : 'Po','婆' : 'Po','破' : 'Po','魄' : 'Po','迫' : 'Po','粕' : 'Po','叵' : 'Po','鄱' : 'Po','珀' : 'Po','钋' : 'Po','钷' : 'Po','皤' : 'Po','笸' : 'Po',
'剖' : 'Pou','裒' : 'Pou','掊' : 'Pou',
'扑' : 'Pu','铺' : 'Pu','仆' : 'Pu','莆' : 'Pu','葡' : 'Pu','菩' : 'Pu','蒲' : 'Pu','埔' : 'Pu','朴' : 'Pu','圃' : 'Pu','普' : 'Pu','浦' : 'Pu','谱' : 'Pu','瀑' : 'Pu','匍' : 'Pu','噗' : 'Pu','溥' : 'Pu','濮' : 'Pu','璞' : 'Pu','氆' : 'Pu','镤' : 'Pu','镨' : 'Pu','蹼' : 'Pu',
'期' : 'Qi','欺' : 'Qi','栖' : 'Qi','戚' : 'Qi','妻' : 'Qi','七' : 'Qi','凄' : 'Qi','漆' : 'Qi','柒' : 'Qi','沏' : 'Qi','其' : 'Qi','棋' : 'Qi','奇' : 'Qi','歧' : 'Qi','畦' : 'Qi','崎' : 'Qi','脐' : 'Qi','齐' : 'Qi','旗' : 'Qi','祈' : 'Qi','祁' : 'Qi','骑' : 'Qi','起' : 'Qi','岂' : 'Qi','乞' : 'Qi','企' : 'Qi','启' : 'Qi','契' : 'Qi','砌' : 'Qi','器' : 'Qi','气' : 'Qi','迄' : 'Qi','弃' : 'Qi','汽' : 'Qi','泣' : 'Qi','讫' : 'Qi','亓' : 'Qi','圻' : 'Qi','芑' : 'Qi','芪' : 'Qi','萁' : 'Qi','萋' : 'Qi','葺' : 'Qi','蕲' : 'Qi','嘁' : 'Qi','屺' : 'Qi','岐' : 'Qi','汔' : 'Qi','淇' : 'Qi','骐' : 'Qi','绮' : 'Qi','琪' : 'Qi','琦' : 'Qi','杞' : 'Qi','桤' : 'Qi','槭' : 'Qi','耆' : 'Qi','祺' : 'Qi','憩' : 'Qi','碛' : 'Qi','颀' : 'Qi','蛴' : 'Qi','蜞' : 'Qi','綦' : 'Qi','鳍' : 'Qi','麒' : 'Qi',
'掐' : 'Qia','恰' : 'Qia','洽' : 'Qia','葜' : 'Qia','袷' : 'Qia','髂' : 'Qia',
'牵' : 'Qian','扦' : 'Qian','钎' : 'Qian','铅' : 'Qian','千' : 'Qian','迁' : 'Qian','签' : 'Qian','仟' : 'Qian','谦' : 'Qian','乾' : 'Qian','黔' : 'Qian','钱' : 'Qian','钳' : 'Qian','前' : 'Qian','潜' : 'Qian','遣' : 'Qian','浅' : 'Qian','谴' : 'Qian','堑' : 'Qian','嵌' : 'Qian','欠' : 'Qian','歉' : 'Qian','倩' : 'Qian','佥' : 'Qian','阡' : 'Qian','芊' : 'Qian','芡' : 'Qian','茜' : 'Qian','掮' : 'Qian','岍' : 'Qian','悭' : 'Qian','慊' : 'Qian','骞' : 'Qian','搴' : 'Qian','褰' : 'Qian','缱' : 'Qian','椠' : 'Qian','肷' : 'Qian','愆' : 'Qian','钤' : 'Qian','虔' : 'Qian','箝' : 'Qian',
'枪' : 'Qiang','呛' : 'Qiang','腔' : 'Qiang','羌' : 'Qiang','墙' : 'Qiang','蔷' : 'Qiang','强' : 'Qiang','抢' : 'Qiang','戕' : 'Qiang','嫱' : 'Qiang','樯' : 'Qiang','戗' : 'Qiang','炝' : 'Qiang','锖' : 'Qiang','锵' : 'Qiang','镪' : 'Qiang','襁' : 'Qiang','蜣' : 'Qiang','羟' : 'Qiang','跄' : 'Qiang',
'橇' : 'Qiao','锹' : 'Qiao','敲' : 'Qiao','悄' : 'Qiao','桥' : 'Qiao','瞧' : 'Qiao','乔' : 'Qiao','侨' : 'Qiao','巧' : 'Qiao','鞘' : 'Qiao','撬' : 'Qiao','翘' : 'Qiao','峭' : 'Qiao','俏' : 'Qiao','窍' : 'Qiao','劁' : 'Qiao','诮' : 'Qiao','谯' : 'Qiao','荞' : 'Qiao','愀' : 'Qiao','憔' : 'Qiao','缲' : 'Qiao','樵' : 'Qiao','硗' : 'Qiao','跷' : 'Qiao','鞒' : 'Qiao',
'切' : 'Qie','茄' : 'Qie','且' : 'Qie','怯' : 'Qie','窃' : 'Qie','郄' : 'Qie','惬' : 'Qie','妾' : 'Qie','挈' : 'Qie','锲' : 'Qie','箧' : 'Qie','趄' : 'Qie',
'钦' : 'Qin','侵' : 'Qin','亲' : 'Qin','秦' : 'Qin','琴' : 'Qin','勤' : 'Qin','芹' : 'Qin','擒' : 'Qin','禽' : 'Qin','寝' : 'Qin','沁' : 'Qin','芩' : 'Qin','揿' : 'Qin','吣' : 'Qin','嗪' : 'Qin','噙' : 'Qin','溱' : 'Qin','檎' : 'Qin','锓' : 'Qin','螓' : 'Qin','衾' : 'Qin',
'青' : 'Qing','轻' : 'Qing','氢' : 'Qing','倾' : 'Qing','卿' : 'Qing','清' : 'Qing','擎' : 'Qing','晴' : 'Qing','氰' : 'Qing','情' : 'Qing','顷' : 'Qing','请' : 'Qing','庆' : 'Qing','苘' : 'Qing','圊' : 'Qing','檠' : 'Qing','磬' : 'Qing','蜻' : 'Qing','罄' : 'Qing','綮' : 'Qing','謦' : 'Qing','鲭' : 'Qing','黥' : 'Qing',
'琼' : 'Qiong','穷' : 'Qiong','邛' : 'Qiong','茕' : 'Qiong','穹' : 'Qiong','蛩' : 'Qiong','筇' : 'Qiong','跫' : 'Qiong','銎' : 'Qiong',
'秋' : 'Qiu','丘' : 'Qiu','邱' : 'Qiu','球' : 'Qiu','求' : 'Qiu','囚' : 'Qiu','酋' : 'Qiu','泅' : 'Qiu','俅' : 'Qiu','巯' : 'Qiu','犰' : 'Qiu','湫' : 'Qiu','逑' : 'Qiu','遒' : 'Qiu','楸' : 'Qiu','赇' : 'Qiu','虬' : 'Qiu','蚯' : 'Qiu','蝤' : 'Qiu','裘' : 'Qiu','糗' : 'Qiu','鳅' : 'Qiu','鼽' : 'Qiu',
'趋' : 'Qu','区' : 'Qu','蛆' : 'Qu','曲' : 'Qu','躯' : 'Qu','屈' : 'Qu','驱' : 'Qu','渠' : 'Qu','取' : 'Qu','娶' : 'Qu','龋' : 'Qu','趣' : 'Qu','去' : 'Qu','诎' : 'Qu','劬' : 'Qu','蕖' : 'Qu','蘧' : 'Qu','岖' : 'Qu','衢' : 'Qu','阒' : 'Qu','璩' : 'Qu','觑' : 'Qu','氍' : 'Qu','朐' : 'Qu','祛' : 'Qu','磲' : 'Qu','鸲' : 'Qu','癯' : 'Qu','蛐' : 'Qu','蠼' : 'Qu','麴' : 'Qu','瞿' : 'Qu','黢' : 'Qu',
'圈' : 'Quan','颧' : 'Quan','权' : 'Quan','醛' : 'Quan','泉' : 'Quan','全' : 'Quan','痊' : 'Quan','拳' : 'Quan','犬' : 'Quan','券' : 'Quan','劝' : 'Quan','诠' : 'Quan','荃' : 'Quan','犭' : 'Quan','悛' : 'Quan','绻' : 'Quan','辁' : 'Quan','畎' : 'Quan','铨' : 'Quan','蜷' : 'Quan','筌' : 'Quan','鬈' : 'Quan',
'缺' : 'Que','炔' : 'Que','瘸' : 'Que','却' : 'Que','鹊' : 'Que','榷' : 'Que','确' : 'Que','雀' : 'Que','阕' : 'Que','阙' : 'Que','悫' : 'Que',
'裙' : 'Qun','群' : 'Qun','逡' : 'Qun',
'然' : 'Ran','燃' : 'Ran','冉' : 'Ran','染' : 'Ran','苒' : 'Ran','蚺' : 'Ran','髯' : 'Ran',
'瓤' : 'Rang','壤' : 'Rang','攘' : 'Rang','嚷' : 'Rang','让' : 'Rang','禳' : 'Rang','穰' : 'Rang',
'饶' : 'Rao','扰' : 'Rao','绕' : 'Rao','荛' : 'Rao','娆' : 'Rao','桡' : 'Rao',
'惹' : 'Re','热' : 'Re',
'壬' : 'Ren','仁' : 'Ren','人' : 'Ren','忍' : 'Ren','韧' : 'Ren','任' : 'Ren','认' : 'Ren','刃' : 'Ren','妊' : 'Ren','纫' : 'Ren','仞' : 'Ren','荏' : 'Ren','饪' : 'Ren','轫' : 'Ren','稔' : 'Ren','衽' : 'Ren',
'扔' : 'Reng','仍' : 'Reng',
'日' : 'Ri',
'戎' : 'Rong','茸' : 'Rong','蓉' : 'Rong','荣' : 'Rong','融' : 'Rong','熔' : 'Rong','溶' : 'Rong','容' : 'Rong','绒' : 'Rong','冗' : 'Rong','嵘' : 'Rong','狨' : 'Rong','榕' : 'Rong','肜' : 'Rong','蝾' : 'Rong',
'揉' : 'Rou','柔' : 'Rou','肉' : 'Rou','糅' : 'Rou','蹂' : 'Rou','鞣' : 'Rou',
'茹' : 'Ru','蠕' : 'Ru','儒' : 'Ru','孺' : 'Ru','如' : 'Ru','辱' : 'Ru','乳' : 'Ru','汝' : 'Ru','入' : 'Ru','褥' : 'Ru','蓐' : 'Ru','薷' : 'Ru','嚅' : 'Ru','洳' : 'Ru','溽' : 'Ru','濡' : 'Ru','缛' : 'Ru','铷' : 'Ru','襦' : 'Ru','颥' : 'Ru',
'软' : 'Ruan','阮' : 'Ruan','朊' : 'Ruan',
'蕊' : 'Rui','瑞' : 'Rui','锐' : 'Rui','芮' : 'Rui','蕤' : 'Rui','枘' : 'Rui','睿' : 'Rui','蚋' : 'Rui',
'闰' : 'Run','润' : 'Run',
'若' : 'Ruo','弱' : 'Ruo','偌' : 'Ruo','箬' : 'Ruo',
'撒' : 'Sa','洒' : 'Sa','萨' : 'Sa','卅' : 'Sa','脎' : 'Sa','飒' : 'Sa',
'腮' : 'Sai','鳃' : 'Sai','塞' : 'Sai','赛' : 'Sai','噻' : 'Sai',
'三' : 'San','叁' : 'San','伞' : 'San','散' : 'San','仨' : 'San','彡' : 'San','馓' : 'San','毵' : 'San',
'桑' : 'Sang','嗓' : 'Sang','丧' : 'Sang','搡' : 'Sang','磉' : 'Sang','颡' : 'Sang',
'搔' : 'Sao','骚' : 'Sao','扫' : 'Sao','嫂' : 'Sao','埽' : 'Sao','缫' : 'Sao','臊' : 'Sao','瘙' : 'Sao','鳋' : 'Sao',
'瑟' : 'Se','色' : 'Se','涩' : 'Se','啬' : 'Se','铯' : 'Se','穑' : 'Se',
'森' : 'Sen',
'僧' : 'Seng',
'莎' : 'Sha','砂' : 'Sha','杀' : 'Sha','刹' : 'Sha','沙' : 'Sha','纱' : 'Sha','傻' : 'Sha','啥' : 'Sha','煞' : 'Sha','唼' : 'Sha','歃' : 'Sha','铩' : 'Sha','痧' : 'Sha','裟' : 'Sha','霎' : 'Sha','鲨' : 'Sha',
'筛' : 'Shai','晒' : 'Shai','酾' : 'Shai',
'珊' : 'Shan','苫' : 'Shan','杉' : 'Shan','山' : 'Shan','删' : 'Shan','煽' : 'Shan','衫' : 'Shan','闪' : 'Shan','陕' : 'Shan','擅' : 'Shan','赡' : 'Shan','膳' : 'Shan','善' : 'Shan','汕' : 'Shan','扇' : 'Shan','缮' : 'Shan','讪' : 'Shan','鄯' : 'Shan','芟' : 'Shan','潸' : 'Shan','姗' : 'Shan','嬗' : 'Shan','骟' : 'Shan','膻' : 'Shan','钐' : 'Shan','疝' : 'Shan','蟮' : 'Shan','舢' : 'Shan','跚' : 'Shan','鳝' : 'Shan',
'墒' : 'Shang','伤' : 'Shang','商' : 'Shang','赏' : 'Shang','晌' : 'Shang','上' : 'Shang','尚' : 'Shang','裳' : 'Shang','垧' : 'Shang','泷' : 'Shang','绱' : 'Shang','殇' : 'Shang','熵' : 'Shang','觞' : 'Shang',
'梢' : 'Shao','捎' : 'Shao','稍' : 'Shao','烧' : 'Shao','芍' : 'Shao','勺' : 'Shao','韶' : 'Shao','少' : 'Shao','哨' : 'Shao','邵' : 'Shao','绍' : 'Shao','劭' : 'Shao','潲' : 'Shao','杓' : 'Shao','筲' : 'Shao','艄' : 'Shao',
'奢' : 'She','赊' : 'She','蛇' : 'She','舌' : 'She','舍' : 'She','赦' : 'She','摄' : 'She','射' : 'She','慑' : 'She','涉' : 'She','社' : 'She','设' : 'She','厍' : 'She','佘' : 'She','揲' : 'She','猞' : 'She','滠' : 'She','麝' : 'She',
'砷' : 'Shen','申' : 'Shen','呻' : 'Shen','伸' : 'Shen','身' : 'Shen','深' : 'Shen','娠' : 'Shen','绅' : 'Shen','神' : 'Shen','沈' : 'Shen','审' : 'Shen','婶' : 'Shen','甚' : 'Shen','肾' : 'Shen','慎' : 'Shen','渗' : 'Shen','什' : 'Shen','诜' : 'Shen','谂' : 'Shen','莘' : 'Shen','葚' : 'Shen','哂' : 'Shen','渖' : 'Shen','椹' : 'Shen','胂' : 'Shen','矧' : 'Shen','蜃' : 'Shen','糁' : 'Shen',
'声' : 'Sheng','生' : 'Sheng','甥' : 'Sheng','牲' : 'Sheng','升' : 'Sheng','绳' : 'Sheng','省' : 'Sheng','盛' : 'Sheng','剩' : 'Sheng','胜' : 'Sheng','圣' : 'Sheng','嵊' : 'Sheng','晟' : 'Sheng','眚' : 'Sheng','笙' : 'Sheng',
'收' : 'Shou','手' : 'Shou','首' : 'Shou','守' : 'Shou','寿' : 'Shou','授' : 'Shou','售' : 'Shou','受' : 'Shou','瘦' : 'Shou','兽' : 'Shou','狩' : 'Shou','绶' : 'Shou','艏' : 'Shou',
'蔬' : 'Shu','枢' : 'Shu','梳' : 'Shu','殊' : 'Shu','抒' : 'Shu','输' : 'Shu','叔' : 'Shu','舒' : 'Shu','淑' : 'Shu','疏' : 'Shu','书' : 'Shu','赎' : 'Shu','孰' : 'Shu','熟' : 'Shu','薯' : 'Shu','暑' : 'Shu','曙' : 'Shu','署' : 'Shu','蜀' : 'Shu','黍' : 'Shu','鼠' : 'Shu','属' : 'Shu','术' : 'Shu','述' : 'Shu','树' : 'Shu','束' : 'Shu','戍' : 'Shu','竖' : 'Shu','墅' : 'Shu','庶' : 'Shu','数' : 'Shu','漱' : 'Shu','恕' : 'Shu','丨' : 'Shu','倏' : 'Shu','塾' : 'Shu','菽' : 'Shu','摅' : 'Shu','沭' : 'Shu','澍' : 'Shu','姝' : 'Shu','纾' : 'Shu','毹' : 'Shu','腧' : 'Shu','殳' : 'Shu','秫' : 'Shu',
'刷' : 'Shua','耍' : 'Shua','唰' : 'Shua',
'摔' : 'Shuai','衰' : 'Shuai','甩' : 'Shuai','帅' : 'Shuai','蟀' : 'Shuai',
'栓' : 'Shuan','拴' : 'Shuan','闩' : 'Shuan','涮' : 'Shuan',
'霜' : 'Shuang','双' : 'Shuang','爽' : 'Shuang','孀' : 'Shuang',
'谁' : 'Shui','水' : 'Shui','睡' : 'Shui','税' : 'Shui',
'吮' : 'Shun','瞬' : 'Shun','顺' : 'Shun','舜' : 'Shun',
'说' : 'Shuo','硕' : 'Shuo','朔' : 'Shuo','烁' : 'Shuo','蒴' : 'Shuo','搠' : 'Shuo','妁' : 'Shuo','槊' : 'Shuo','铄' : 'Shuo',
'斯' : 'Si','撕' : 'Si','嘶' : 'Si','思' : 'Si','私' : 'Si','司' : 'Si','丝' : 'Si','死' : 'Si','肆' : 'Si','寺' : 'Si','嗣' : 'Si','四' : 'Si','伺' : 'Si','似' : 'Si','饲' : 'Si','巳' : 'Si','厮' : 'Si','俟' : 'Si','兕' : 'Si','厶' : 'Si','咝' : 'Si','汜' : 'Si','泗' : 'Si','澌' : 'Si','姒' : 'Si','驷' : 'Si','缌' : 'Si','祀' : 'Si','锶' : 'Si','鸶' : 'Si','耜' : 'Si','蛳' : 'Si','笥' : 'Si',
'松' : 'Song','耸' : 'Song','怂' : 'Song','颂' : 'Song','送' : 'Song','宋' : 'Song','讼' : 'Song','诵' : 'Song','凇' : 'Song','菘' : 'Song','崧' : 'Song','嵩' : 'Song','忪' : 'Song','悚' : 'Song','淞' : 'Song','竦' : 'Song',
'搜' : 'Sou','艘' : 'Sou','擞' : 'Sou','嗽' : 'Sou','叟' : 'Sou','薮' : 'Sou','嗖' : 'Sou','嗾' : 'Sou','馊' : 'Sou','溲' : 'Sou','飕' : 'Sou','瞍' : 'Sou','锼' : 'Sou','螋' : 'Sou',
'苏' : 'Su','酥' : 'Su','俗' : 'Su','素' : 'Su','速' : 'Su','粟' : 'Su','僳' : 'Su','塑' : 'Su','溯' : 'Su','宿' : 'Su','诉' : 'Su','肃' : 'Su','夙' : 'Su','谡' : 'Su','蔌' : 'Su','嗉' : 'Su','愫' : 'Su','涑' : 'Su','簌' : 'Su','觫' : 'Su','稣' : 'Su',
'酸' : 'Suan','蒜' : 'Suan','算' : 'Suan','狻' : 'Suan',
'虽' : 'Sui','隋' : 'Sui','随' : 'Sui','绥' : 'Sui','髓' : 'Sui','碎' : 'Sui','岁' : 'Sui','穗' : 'Sui','遂' : 'Sui','隧' : 'Sui','祟' : 'Sui','谇' : 'Sui','荽' : 'Sui','濉' : 'Sui','邃' : 'Sui','燧' : 'Sui','眭' : 'Sui','睢' : 'Sui',
'孙' : 'Sun','损' : 'Sun','笋' : 'Sun','荪' : 'Sun','狲' : 'Sun','飧' : 'Sun','榫' : 'Sun','隼' : 'Sun',
'蓑' : 'Suo','梭' : 'Suo','唆' : 'Suo','缩' : 'Suo','琐' : 'Suo','索' : 'Suo','锁' : 'Suo','所' : 'Suo','唢' : 'Suo','嗦' : 'Suo','嗍' : 'Suo','娑' : 'Suo','桫' : 'Suo','挲' : 'Suo','睃' : 'Suo','羧' : 'Suo',
'塌' : 'Ta','他' : 'Ta','它' : 'Ta','她' : 'Ta','塔' : 'Ta','獭' : 'Ta','挞' : 'Ta','蹋' : 'Ta','踏' : 'Ta','嗒' : 'Ta','闼' : 'Ta','溻' : 'Ta','遢' : 'Ta','榻' : 'Ta','沓' : 'Ta','铊' : 'Ta','趿' : 'Ta','鳎' : 'Ta',
'胎' : 'Tai','苔' : 'Tai','抬' : 'Tai','台' : 'Tai','泰' : 'Tai','酞' : 'Tai','太' : 'Tai','态' : 'Tai','汰' : 'Tai','邰' : 'Tai','薹' : 'Tai','骀' : 'Tai','肽' : 'Tai','炱' : 'Tai','钛' : 'Tai','跆' : 'Tai','鲐' : 'Tai',
'汤' : 'Tang','塘' : 'Tang','搪' : 'Tang','堂' : 'Tang','棠' : 'Tang','膛' : 'Tang','唐' : 'Tang','糖' : 'Tang','倘' : 'Tang','躺' : 'Tang','淌' : 'Tang','趟' : 'Tang','烫' : 'Tang','傥' : 'Tang','帑' : 'Tang','溏' : 'Tang','瑭' : 'Tang','樘' : 'Tang','铴' : 'Tang','镗' : 'Tang','耥' : 'Tang','螗' : 'Tang','螳' : 'Tang','羰' : 'Tang','醣' : 'Tang',
'掏' : 'Tao','涛' : 'Tao','滔' : 'Tao','绦' : 'Tao','萄' : 'Tao','桃' : 'Tao','逃' : 'Tao','淘' : 'Tao','陶' : 'Tao','讨' : 'Tao','套' : 'Tao','鼗' : 'Tao','啕' : 'Tao','洮' : 'Tao','韬' : 'Tao','饕' : 'Tao',
'特' : 'Te','忑' : 'Te','慝' : 'Te','铽' : 'Te',
'藤' : 'Teng','腾' : 'Teng','疼' : 'Teng','誊' : 'Teng','滕' : 'Teng',
'梯' : 'Ti','剔' : 'Ti','踢' : 'Ti','锑' : 'Ti','提' : 'Ti','题' : 'Ti','蹄' : 'Ti','啼' : 'Ti','体' : 'Ti','替' : 'Ti','嚏' : 'Ti','惕' : 'Ti','涕' : 'Ti','剃' : 'Ti','屉' : 'Ti','倜' : 'Ti','悌' : 'Ti','逖' : 'Ti','绨' : 'Ti','缇' : 'Ti','鹈' : 'Ti','裼' : 'Ti','醍' : 'Ti',
'天' : 'Tian','添' : 'Tian','填' : 'Tian','田' : 'Tian','甜' : 'Tian','恬' : 'Tian','舔' : 'Tian','腆' : 'Tian','掭' : 'Tian','忝' : 'Tian','阗' : 'Tian','殄' : 'Tian','畋' : 'Tian',
'贴' : 'Tie','铁' : 'Tie','帖' : 'Tie','萜' : 'Tie','餮' : 'Tie',
'厅' : 'Ting','听' : 'Ting','烃' : 'Ting','汀' : 'Ting','廷' : 'Ting','停' : 'Ting','亭' : 'Ting','庭' : 'Ting','挺' : 'Ting','艇' : 'Ting','莛' : 'Ting','葶' : 'Ting','婷' : 'Ting','梃' : 'Ting','铤' : 'Ting','蜓' : 'Ting','霆' : 'Ting',
'通' : 'Tong','桐' : 'Tong','酮' : 'Tong','瞳' : 'Tong','同' : 'Tong','铜' : 'Tong','彤' : 'Tong','童' : 'Tong','桶' : 'Tong','捅' : 'Tong','筒' : 'Tong','统' : 'Tong','痛' : 'Tong','佟' : 'Tong','仝' : 'Tong','茼' : 'Tong','嗵' : 'Tong','恸' : 'Tong','潼' : 'Tong','砼' : 'Tong',
'偷' : 'Tou','投' : 'Tou','头' : 'Tou','透' : 'Tou','骰' : 'Tou',
'凸' : 'Tu','秃' : 'Tu','突' : 'Tu','图' : 'Tu','徒' : 'Tu','途' : 'Tu','涂' : 'Tu','屠' : 'Tu','土' : 'Tu','吐' : 'Tu','兔' : 'Tu','堍' : 'Tu','荼' : 'Tu','菟' : 'Tu','钍' : 'Tu','酴' : 'Tu',
'湍' : 'Tuan','团' : 'Tuan','抟' : 'Tuan','彖' : 'Tuan','疃' : 'Tuan',
'推' : 'Tui','颓' : 'Tui','腿' : 'Tui','蜕' : 'Tui','褪' : 'Tui','退' : 'Tui','忒' : 'Tui','煺' : 'Tui',
'拖' : 'Tuo','托' : 'Tuo','脱' : 'Tuo','鸵' : 'Tuo','陀' : 'Tuo','驮' : 'Tuo','驼' : 'Tuo','椭' : 'Tuo','妥' : 'Tuo','拓' : 'Tuo','唾' : 'Tuo','佗' : 'Tuo','坨' : 'Tuo','庹' : 'Tuo','沱' : 'Tuo','柝' : 'Tuo','柁' : 'Tuo','橐' : 'Tuo','砣' : 'Tuo','箨' : 'Tuo','酡' : 'Tuo','跎' : 'Tuo','鼍' : 'Tuo',
'挖' : 'Wa','哇' : 'Wa','蛙' : 'Wa','洼' : 'Wa','娃' : 'Wa','瓦' : 'Wa','袜' : 'Wa','佤' : 'Wa','娲' : 'Wa','腽' : 'Wa',
'歪' : 'Wai','外' : 'Wai','崴' : 'Wai',
'豌' : 'Wan','弯' : 'Wan','湾' : 'Wan','玩' : 'Wan','顽' : 'Wan','丸' : 'Wan','烷' : 'Wan','完' : 'Wan','碗' : 'Wan','挽' : 'Wan','晚' : 'Wan','皖' : 'Wan','惋' : 'Wan','宛' : 'Wan','婉' : 'Wan','万' : 'Wan','腕' : 'Wan','剜' : 'Wan','芄' : 'Wan','菀' : 'Wan','纨' : 'Wan','绾' : 'Wan','琬' : 'Wan','脘' : 'Wan','畹' : 'Wan','蜿' : 'Wan',
'汪' : 'Wang','王' : 'Wang','亡' : 'Wang','枉' : 'Wang','网' : 'Wang','往' : 'Wang','旺' : 'Wang','望' : 'Wang','忘' : 'Wang','妄' : 'Wang','罔' : 'Wang','惘' : 'Wang','辋' : 'Wang','魍' : 'Wang',
'威' : 'Wei','巍' : 'Wei','微' : 'Wei','危' : 'Wei','韦' : 'Wei','违' : 'Wei','桅' : 'Wei','围' : 'Wei','唯' : 'Wei','惟' : 'Wei','为' : 'Wei','潍' : 'Wei','维' : 'Wei','苇' : 'Wei','萎' : 'Wei','委' : 'Wei','伟' : 'Wei','伪' : 'Wei','尾' : 'Wei','纬' : 'Wei','未' : 'Wei','蔚' : 'Wei','味' : 'Wei','畏' : 'Wei','胃' : 'Wei','喂' : 'Wei','魏' : 'Wei','位' : 'Wei','渭' : 'Wei','谓' : 'Wei','尉' : 'Wei','慰' : 'Wei','卫' : 'Wei','偎' : 'Wei','诿' : 'Wei','隈' : 'Wei','葳' : 'Wei','薇' : 'Wei','帏' : 'Wei','帷' : 'Wei','嵬' : 'Wei','猥' : 'Wei','猬' : 'Wei','闱' : 'Wei','沩' : 'Wei','洧' : 'Wei','涠' : 'Wei','逶' : 'Wei','娓' : 'Wei','玮' : 'Wei','韪' : 'Wei','軎' : 'Wei','炜' : 'Wei','煨' : 'Wei','痿' : 'Wei','艉' : 'Wei','鲔' : 'Wei',
'瘟' : 'Wen','温' : 'Wen','蚊' : 'Wen','文' : 'Wen','闻' : 'Wen','纹' : 'Wen','吻' : 'Wen','稳' : 'Wen','紊' : 'Wen','问' : 'Wen','刎' : 'Wen','阌' : 'Wen','汶' : 'Wen','璺' : 'Wen','攵' : 'Wen','雯' : 'Wen',
'嗡' : 'Weng','翁' : 'Weng','瓮' : 'Weng','蓊' : 'Weng','蕹' : 'Weng',
'挝' : 'Wo','蜗' : 'Wo','涡' : 'Wo','窝' : 'Wo','我' : 'Wo','斡' : 'Wo','卧' : 'Wo','握' : 'Wo','沃' : 'Wo','倭' : 'Wo','莴' : 'Wo','喔' : 'Wo','幄' : 'Wo','渥' : 'Wo','肟' : 'Wo','硪' : 'Wo','龌' : 'Wo',
'巫' : 'Wu','呜' : 'Wu','钨' : 'Wu','乌' : 'Wu','污' : 'Wu','诬' : 'Wu','屋' : 'Wu','无' : 'Wu','芜' : 'Wu','梧' : 'Wu','吾' : 'Wu','吴' : 'Wu','毋' : 'Wu','武' : 'Wu','五' : 'Wu','捂' : 'Wu','午' : 'Wu','舞' : 'Wu','伍' : 'Wu','侮' : 'Wu','坞' : 'Wu','戊' : 'Wu','雾' : 'Wu','晤' : 'Wu','物' : 'Wu','勿' : 'Wu','务' : 'Wu','悟' : 'Wu','误' : 'Wu','兀' : 'Wu','仵' : 'Wu','阢' : 'Wu','邬' : 'Wu','圬' : 'Wu','芴' : 'Wu','唔' : 'Wu','庑' : 'Wu','怃' : 'Wu','忤' : 'Wu','寤' : 'Wu','迕' : 'Wu','妩' : 'Wu','婺' : 'Wu','骛' : 'Wu','杌' : 'Wu','牾' : 'Wu','焐' : 'Wu','鹉' : 'Wu','鹜' : 'Wu','痦' : 'Wu','蜈' : 'Wu','鋈' : 'Wu','鼯' : 'Wu',
'昔' : 'Xi','熙' : 'Xi','析' : 'Xi','西' : 'Xi','硒' : 'Xi','矽' : 'Xi','晰' : 'Xi','嘻' : 'Xi','吸' : 'Xi','锡' : 'Xi','牺' : 'Xi','稀' : 'Xi','息' : 'Xi','希' : 'Xi','悉' : 'Xi','膝' : 'Xi','夕' : 'Xi','惜' : 'Xi','熄' : 'Xi','烯' : 'Xi','溪' : 'Xi','汐' : 'Xi','犀' : 'Xi','檄' : 'Xi','袭' : 'Xi','席' : 'Xi','习' : 'Xi','媳' : 'Xi','喜' : 'Xi','铣' : 'Xi','洗' : 'Xi','系' : 'Xi','隙' : 'Xi','戏' : 'Xi','细' : 'Xi','僖' : 'Xi','兮' : 'Xi','隰' : 'Xi','郗' : 'Xi','菥' : 'Xi','葸' : 'Xi','蓰' : 'Xi','奚' : 'Xi','唏' : 'Xi','徙' : 'Xi','饩' : 'Xi','阋' : 'Xi','浠' : 'Xi','淅' : 'Xi','屣' : 'Xi','嬉' : 'Xi','玺' : 'Xi','樨' : 'Xi','曦' : 'Xi','觋' : 'Xi','欷' : 'Xi','歙' : 'Xi','熹' : 'Xi','禊' : 'Xi','禧' : 'Xi','皙' : 'Xi','穸' : 'Xi','蜥' : 'Xi','螅' : 'Xi','蟋' : 'Xi','舄' : 'Xi','舾' : 'Xi','羲' : 'Xi','粞' : 'Xi','翕' : 'Xi','醯' : 'Xi','蹊' : 'Xi','鼷' : 'Xi',
'瞎' : 'Xia','虾' : 'Xia','匣' : 'Xia','霞' : 'Xia','辖' : 'Xia','暇' : 'Xia','峡' : 'Xia','侠' : 'Xia','狭' : 'Xia','下' : 'Xia','厦' : 'Xia','夏' : 'Xia','吓' : 'Xia','呷' : 'Xia','狎' : 'Xia','遐' : 'Xia','瑕' : 'Xia','柙' : 'Xia','硖' : 'Xia','罅' : 'Xia','黠' : 'Xia',
'掀' : 'Xian','锨' : 'Xian','先' : 'Xian','仙' : 'Xian','鲜' : 'Xian','纤' : 'Xian','咸' : 'Xian','贤' : 'Xian','衔' : 'Xian','舷' : 'Xian','闲' : 'Xian','涎' : 'Xian','弦' : 'Xian','嫌' : 'Xian','显' : 'Xian','险' : 'Xian','现' : 'Xian','献' : 'Xian','县' : 'Xian','腺' : 'Xian','馅' : 'Xian','羡' : 'Xian','宪' : 'Xian','陷' : 'Xian','限' : 'Xian','线' : 'Xian','冼' : 'Xian','苋' : 'Xian','莶' : 'Xian','藓' : 'Xian','岘' : 'Xian','猃' : 'Xian','暹' : 'Xian','娴' : 'Xian','氙' : 'Xian','燹' : 'Xian','祆' : 'Xian','鹇' : 'Xian','痫' : 'Xian','蚬' : 'Xian','筅' : 'Xian','籼' : 'Xian','酰' : 'Xian','跣' : 'Xian','跹' : 'Xian','霰' : 'Xian',
'相' : 'Xiang','厢' : 'Xiang','镶' : 'Xiang','香' : 'Xiang','箱' : 'Xiang','襄' : 'Xiang','湘' : 'Xiang','乡' : 'Xiang','翔' : 'Xiang','祥' : 'Xiang','详' : 'Xiang','想' : 'Xiang','响' : 'Xiang','享' : 'Xiang','项' : 'Xiang','巷' : 'Xiang','橡' : 'Xiang','像' : 'Xiang','向' : 'Xiang','象' : 'Xiang','芗' : 'Xiang','葙' : 'Xiang','饷' : 'Xiang','庠' : 'Xiang','骧' : 'Xiang','缃' : 'Xiang','蟓' : 'Xiang','鲞' : 'Xiang','飨' : 'Xiang',
'萧' : 'Xiao','硝' : 'Xiao','霄' : 'Xiao','削' : 'Xiao','哮' : 'Xiao','嚣' : 'Xiao','销' : 'Xiao','消' : 'Xiao','宵' : 'Xiao','淆' : 'Xiao','晓' : 'Xiao','小' : 'Xiao','孝' : 'Xiao','校' : 'Xiao','肖' : 'Xiao','啸' : 'Xiao','笑' : 'Xiao','效' : 'Xiao','哓' : 'Xiao','崤' : 'Xiao','潇' : 'Xiao','逍' : 'Xiao','骁' : 'Xiao','绡' : 'Xiao','枭' : 'Xiao','枵' : 'Xiao','蛸' : 'Xiao','筱' : 'Xiao','箫' : 'Xiao','魈' : 'Xiao',
'楔' : 'Xie','些' : 'Xie','歇' : 'Xie','蝎' : 'Xie','鞋' : 'Xie','协' : 'Xie','挟' : 'Xie','携' : 'Xie','邪' : 'Xie','斜' : 'Xie','胁' : 'Xie','谐' : 'Xie','写' : 'Xie','械' : 'Xie','卸' : 'Xie','蟹' : 'Xie','懈' : 'Xie','泄' : 'Xie','泻' : 'Xie','谢' : 'Xie','屑' : 'Xie','偕' : 'Xie','亵' : 'Xie','勰' : 'Xie','燮' : 'Xie','薤' : 'Xie','撷' : 'Xie','獬' : 'Xie','廨' : 'Xie','渫' : 'Xie','瀣' : 'Xie','邂' : 'Xie','绁' : 'Xie','缬' : 'Xie','榭' : 'Xie','榍' : 'Xie','蹀' : 'Xie','躞' : 'Xie',
'薪' : 'Xin','芯' : 'Xin','锌' : 'Xin','欣' : 'Xin','辛' : 'Xin','新' : 'Xin','忻' : 'Xin','心' : 'Xin','信' : 'Xin','衅' : 'Xin','囟' : 'Xin','馨' : 'Xin','昕' : 'Xin','歆' : 'Xin','镡' : 'Xin','鑫' : 'Xin',
'星' : 'Xing','腥' : 'Xing','猩' : 'Xing','惺' : 'Xing','兴' : 'Xing','刑' : 'Xing','型' : 'Xing','形' : 'Xing','邢' : 'Xing','醒' : 'Xing','幸' : 'Xing','杏' : 'Xing','性' : 'Xing','姓' : 'Xing','陉' : 'Xing','荇' : 'Xing','荥' : 'Xing','擤' : 'Xing','饧' : 'Xing','悻' : 'Xing','硎' : 'Xing',
'兄' : 'Xiong','凶' : 'Xiong','胸' : 'Xiong','匈' : 'Xiong','汹' : 'Xiong','雄' : 'Xiong','熊' : 'Xiong','芎' : 'Xiong',
'休' : 'Xiu','修' : 'Xiu','羞' : 'Xiu','朽' : 'Xiu','嗅' : 'Xiu','锈' : 'Xiu','秀' : 'Xiu','袖' : 'Xiu','绣' : 'Xiu','咻' : 'Xiu','岫' : 'Xiu','馐' : 'Xiu','庥' : 'Xiu','溴' : 'Xiu','鸺' : 'Xiu','貅' : 'Xiu','髹' : 'Xiu',
'墟' : 'Xu','戌' : 'Xu','需' : 'Xu','虚' : 'Xu','嘘' : 'Xu','须' : 'Xu','徐' : 'Xu','许' : 'Xu','蓄' : 'Xu','酗' : 'Xu','叙' : 'Xu','旭' : 'Xu','序' : 'Xu','畜' : 'Xu','恤' : 'Xu','絮' : 'Xu','婿' : 'Xu','绪' : 'Xu','续' : 'Xu','诩' : 'Xu','勖' : 'Xu','圩' : 'Xu','蓿' : 'Xu','洫' : 'Xu','溆' : 'Xu','顼' : 'Xu','栩' : 'Xu','煦' : 'Xu','盱' : 'Xu','胥' : 'Xu','糈' : 'Xu','醑' : 'Xu',
'轩' : 'Xuan','喧' : 'Xuan','宣' : 'Xuan','悬' : 'Xuan','旋' : 'Xuan','玄' : 'Xuan','选' : 'Xuan','癣' : 'Xuan','眩' : 'Xuan','绚' : 'Xuan','儇' : 'Xuan','谖' : 'Xuan','萱' : 'Xuan','揎' : 'Xuan','泫' : 'Xuan','渲' : 'Xuan','漩' : 'Xuan','璇' : 'Xuan','楦' : 'Xuan','暄' : 'Xuan','炫' : 'Xuan','煊' : 'Xuan','碹' : 'Xuan','铉' : 'Xuan','镟' : 'Xuan','痃' : 'Xuan',
'靴' : 'Xue','薛' : 'Xue','学' : 'Xue','穴' : 'Xue','雪' : 'Xue','血' : 'Xue','谑' : 'Xue','噱' : 'Xue','泶' : 'Xue','踅' : 'Xue','鳕' : 'Xue',
'勋' : 'Xun','熏' : 'Xun','循' : 'Xun','旬' : 'Xun','询' : 'Xun','寻' : 'Xun','驯' : 'Xun','巡' : 'Xun','殉' : 'Xun','汛' : 'Xun','训' : 'Xun','讯' : 'Xun','逊' : 'Xun','迅' : 'Xun','巽' : 'Xun','郇' : 'Xun','埙' : 'Xun','荀' : 'Xun','荨' : 'Xun','蕈' : 'Xun','薰' : 'Xun','峋' : 'Xun','徇' : 'Xun','獯' : 'Xun','恂' : 'Xun','洵' : 'Xun','浔' : 'Xun','曛' : 'Xun','醺' : 'Xun','鲟' : 'Xun',
'压' : 'Ya','押' : 'Ya','鸦' : 'Ya','鸭' : 'Ya','呀' : 'Ya','丫' : 'Ya','芽' : 'Ya','牙' : 'Ya','蚜' : 'Ya','崖' : 'Ya','衙' : 'Ya','涯' : 'Ya','雅' : 'Ya','哑' : 'Ya','亚' : 'Ya','讶' : 'Ya','伢' : 'Ya','垭' : 'Ya','揠' : 'Ya','岈' : 'Ya','迓' : 'Ya','娅' : 'Ya','琊' : 'Ya','桠' : 'Ya','氩' : 'Ya','砑' : 'Ya','睚' : 'Ya','痖' : 'Ya',
'焉' : 'Yan','咽' : 'Yan','阉' : 'Yan','烟' : 'Yan','淹' : 'Yan','盐' : 'Yan','严' : 'Yan','研' : 'Yan','蜒' : 'Yan','岩' : 'Yan','延' : 'Yan','言' : 'Yan','颜' : 'Yan','阎' : 'Yan','炎' : 'Yan','沿' : 'Yan','奄' : 'Yan','掩' : 'Yan','眼' : 'Yan','衍' : 'Yan','演' : 'Yan','艳' : 'Yan','堰' : 'Yan','燕' : 'Yan','厌' : 'Yan','砚' : 'Yan','雁' : 'Yan','唁' : 'Yan','彦' : 'Yan','焰' : 'Yan','宴' : 'Yan','谚' : 'Yan','验' : 'Yan','厣' : 'Yan','赝' : 'Yan','剡' : 'Yan','俨' : 'Yan','偃' : 'Yan','兖' : 'Yan','谳' : 'Yan','郾' : 'Yan','鄢' : 'Yan','埏' : 'Yan','菸' : 'Yan','崦' : 'Yan','恹' : 'Yan','闫' : 'Yan','阏' : 'Yan','湮' : 'Yan','滟' : 'Yan','妍' : 'Yan','嫣' : 'Yan','琰' : 'Yan','檐' : 'Yan','晏' : 'Yan','胭' : 'Yan','焱' : 'Yan','罨' : 'Yan','筵' : 'Yan','酽' : 'Yan','趼' : 'Yan','魇' : 'Yan','餍' : 'Yan','鼹' : 'Yan',
'殃' : 'Yang','央' : 'Yang','鸯' : 'Yang','秧' : 'Yang','杨' : 'Yang','扬' : 'Yang','佯' : 'Yang','疡' : 'Yang','羊' : 'Yang','洋' : 'Yang','阳' : 'Yang','氧' : 'Yang','仰' : 'Yang','痒' : 'Yang','养' : 'Yang','样' : 'Yang','漾' : 'Yang','徉' : 'Yang','怏' : 'Yang','泱' : 'Yang','炀' : 'Yang','烊' : 'Yang','恙' : 'Yang','蛘' : 'Yang','鞅' : 'Yang',
'邀' : 'Yao','腰' : 'Yao','妖' : 'Yao','瑶' : 'Yao','摇' : 'Yao','尧' : 'Yao','遥' : 'Yao','窑' : 'Yao','谣' : 'Yao','姚' : 'Yao','咬' : 'Yao','舀' : 'Yao','药' : 'Yao','要' : 'Yao','耀' : 'Yao','钥' : 'Yao','夭' : 'Yao','爻' : 'Yao','吆' : 'Yao','崾' : 'Yao','徭' : 'Yao','幺' : 'Yao','珧' : 'Yao','杳' : 'Yao','轺' : 'Yao','曜' : 'Yao','肴' : 'Yao','铫' : 'Yao','鹞' : 'Yao','窈' : 'Yao','鳐' : 'Yao',
'椰' : 'Ye','噎' : 'Ye','耶' : 'Ye','爷' : 'Ye','野' : 'Ye','冶' : 'Ye','也' : 'Ye','页' : 'Ye','掖' : 'Ye','业' : 'Ye','叶' : 'Ye','曳' : 'Ye','腋' : 'Ye','夜' : 'Ye','液' : 'Ye','靥' : 'Ye','谒' : 'Ye','邺' : 'Ye','揶' : 'Ye','晔' : 'Ye','烨' : 'Ye','铘' : 'Ye',
'一' : 'Yi','壹' : 'Yi','医' : 'Yi','揖' : 'Yi','铱' : 'Yi','依' : 'Yi','伊' : 'Yi','衣' : 'Yi','颐' : 'Yi','夷' : 'Yi','遗' : 'Yi','移' : 'Yi','仪' : 'Yi','胰' : 'Yi','疑' : 'Yi','沂' : 'Yi','宜' : 'Yi','姨' : 'Yi','彝' : 'Yi','椅' : 'Yi','蚁' : 'Yi','倚' : 'Yi','已' : 'Yi','乙' : 'Yi','矣' : 'Yi','以' : 'Yi','艺' : 'Yi','抑' : 'Yi','易' : 'Yi','邑' : 'Yi','屹' : 'Yi','亿' : 'Yi','役' : 'Yi','臆' : 'Yi','逸' : 'Yi','肄' : 'Yi','疫' : 'Yi','亦' : 'Yi','裔' : 'Yi','意' : 'Yi','毅' : 'Yi','忆' : 'Yi','义' : 'Yi','益' : 'Yi','溢' : 'Yi','诣' : 'Yi','议' : 'Yi','谊' : 'Yi','译' : 'Yi','异' : 'Yi','翼' : 'Yi','翌' : 'Yi','绎' : 'Yi','刈' : 'Yi','劓' : 'Yi','佚' : 'Yi','佾' : 'Yi','诒' : 'Yi','圯' : 'Yi','埸' : 'Yi','懿' : 'Yi','苡' : 'Yi','荑' : 'Yi','薏' : 'Yi','弈' : 'Yi','奕' : 'Yi','挹' : 'Yi','弋' : 'Yi','呓' : 'Yi','咦' : 'Yi','咿' : 'Yi','噫' : 'Yi','峄' : 'Yi','嶷' : 'Yi','猗' : 'Yi','饴' : 'Yi','怿' : 'Yi','怡' : 'Yi','悒' : 'Yi','漪' : 'Yi','迤' : 'Yi','驿' : 'Yi','缢' : 'Yi','殪' : 'Yi','轶' : 'Yi','贻' : 'Yi','欹' : 'Yi','旖' : 'Yi','熠' : 'Yi','眙' : 'Yi','钇' : 'Yi','镒' : 'Yi','镱' : 'Yi','痍' : 'Yi','瘗' : 'Yi','癔' : 'Yi','翊' : 'Yi','蜴' : 'Yi','舣' : 'Yi','羿' : 'Yi',
'茵' : 'Yin','荫' : 'Yin','因' : 'Yin','殷' : 'Yin','音' : 'Yin','阴' : 'Yin','姻' : 'Yin','吟' : 'Yin','银' : 'Yin','淫' : 'Yin','寅' : 'Yin','饮' : 'Yin','尹' : 'Yin','引' : 'Yin','隐' : 'Yin','印' : 'Yin','胤' : 'Yin','鄞' : 'Yin','垠' : 'Yin','堙' : 'Yin','茚' : 'Yin','吲' : 'Yin','喑' : 'Yin','狺' : 'Yin','夤' : 'Yin','洇' : 'Yin','氤' : 'Yin','铟' : 'Yin','瘾' : 'Yin','窨' : 'Yin','蚓' : 'Yin','霪' : 'Yin','龈' : 'Yin',
'英' : 'Ying','樱' : 'Ying','婴' : 'Ying','鹰' : 'Ying','应' : 'Ying','缨' : 'Ying','莹' : 'Ying','萤' : 'Ying','营' : 'Ying','荧' : 'Ying','蝇' : 'Ying','迎' : 'Ying','赢' : 'Ying','盈' : 'Ying','影' : 'Ying','颖' : 'Ying','硬' : 'Ying','映' : 'Ying','嬴' : 'Ying','郢' : 'Ying','茔' : 'Ying','莺' : 'Ying','萦' : 'Ying','蓥' : 'Ying','撄' : 'Ying','嘤' : 'Ying','膺' : 'Ying','滢' : 'Ying','潆' : 'Ying','瀛' : 'Ying','瑛' : 'Ying','璎' : 'Ying','楹' : 'Ying','媵' : 'Ying','鹦' : 'Ying','瘿' : 'Ying','颍' : 'Ying','罂' : 'Ying',
'哟' : 'Yo','唷' : 'Yo',
'拥' : 'Yong','佣' : 'Yong','臃' : 'Yong','痈' : 'Yong','庸' : 'Yong','雍' : 'Yong','踊' : 'Yong','蛹' : 'Yong','咏' : 'Yong','泳' : 'Yong','涌' : 'Yong','永' : 'Yong','恿' : 'Yong','勇' : 'Yong','用' : 'Yong','俑' : 'Yong','壅' : 'Yong','墉' : 'Yong','喁' : 'Yong','慵' : 'Yong','邕' : 'Yong','镛' : 'Yong','甬' : 'Yong','鳙' : 'Yong','饔' : 'Yong',
'幽' : 'You','优' : 'You','悠' : 'You','忧' : 'You','尤' : 'You','由' : 'You','邮' : 'You','铀' : 'You','犹' : 'You','油' : 'You','游' : 'You','酉' : 'You','有' : 'You','友' : 'You','右' : 'You','佑' : 'You','釉' : 'You','诱' : 'You','又' : 'You','幼' : 'You','卣' : 'You','攸' : 'You','侑' : 'You','莠' : 'You','莜' : 'You','莸' : 'You','尢' : 'You','呦' : 'You','囿' : 'You','宥' : 'You','柚' : 'You','猷' : 'You','牖' : 'You','铕' : 'You','疣' : 'You','蚰' : 'You','蚴' : 'You','蝣' : 'You','繇' : 'You','鱿' : 'You','黝' : 'You','鼬' : 'You',
'迂' : 'Yu','淤' : 'Yu','于' : 'Yu','盂' : 'Yu','榆' : 'Yu','虞' : 'Yu','愚' : 'Yu','舆' : 'Yu','余' : 'Yu','俞' : 'Yu','逾' : 'Yu','鱼' : 'Yu','愉' : 'Yu','渝' : 'Yu','渔' : 'Yu','隅' : 'Yu','予' : 'Yu','娱' : 'Yu','雨' : 'Yu','与' : 'Yu','屿' : 'Yu','禹' : 'Yu','宇' : 'Yu','语' : 'Yu','羽' : 'Yu','玉' : 'Yu','域' : 'Yu','芋' : 'Yu','郁' : 'Yu','吁' : 'Yu','遇' : 'Yu','喻' : 'Yu','峪' : 'Yu','御' : 'Yu','愈' : 'Yu','欲' : 'Yu','狱' : 'Yu','育' : 'Yu','誉' : 'Yu','浴' : 'Yu','寓' : 'Yu','裕' : 'Yu','预' : 'Yu','豫' : 'Yu','驭' : 'Yu','禺' : 'Yu','毓' : 'Yu','伛' : 'Yu','俣' : 'Yu','谀' : 'Yu','谕' : 'Yu','萸' : 'Yu','蓣' : 'Yu','揄' : 'Yu','圄' : 'Yu','圉' : 'Yu','嵛' : 'Yu','狳' : 'Yu','饫' : 'Yu','馀' : 'Yu','庾' : 'Yu','阈' : 'Yu','鬻' : 'Yu','妪' : 'Yu','妤' : 'Yu','纡' : 'Yu','瑜' : 'Yu','昱' : 'Yu','觎' : 'Yu','腴' : 'Yu','欤' : 'Yu','於' : 'Yu','煜' : 'Yu','燠' : 'Yu','聿' : 'Yu','畲' : 'Yu','钰' : 'Yu','鹆' : 'Yu','鹬' : 'Yu','瘐' : 'Yu','瘀' : 'Yu','窬' : 'Yu','窳' : 'Yu','蜮' : 'Yu','蝓' : 'Yu','竽' : 'Yu','臾' : 'Yu','舁' : 'Yu','雩' : 'Yu','龉' : 'Yu',
'鸳' : 'Yuan','渊' : 'Yuan','冤' : 'Yuan','元' : 'Yuan','垣' : 'Yuan','袁' : 'Yuan','原' : 'Yuan','援' : 'Yuan','辕' : 'Yuan','园' : 'Yuan','员' : 'Yuan','圆' : 'Yuan','猿' : 'Yuan','源' : 'Yuan','缘' : 'Yuan','远' : 'Yuan','苑' : 'Yuan','愿' : 'Yuan','怨' : 'Yuan','院' : 'Yuan','垸' : 'Yuan','塬' : 'Yuan','芫' : 'Yuan','掾' : 'Yuan','沅' : 'Yuan','媛' : 'Yuan','瑗' : 'Yuan','橼' : 'Yuan','爰' : 'Yuan','眢' : 'Yuan','鸢' : 'Yuan','螈' : 'Yuan','箢' : 'Yuan','鼋' : 'Yuan',
'耘' : 'Yun','云' : 'Yun','郧' : 'Yun','匀' : 'Yun','陨' : 'Yun','允' : 'Yun','运' : 'Yun','蕴' : 'Yun','酝' : 'Yun','晕' : 'Yun','韵' : 'Yun','孕' : 'Yun','郓' : 'Yun','芸' : 'Yun','狁' : 'Yun','恽' : 'Yun','愠' : 'Yun','纭' : 'Yun','韫' : 'Yun','殒' : 'Yun','昀' : 'Yun','氲' : 'Yun','熨' : 'Yun',
'匝' : 'Za','砸' : 'Za','杂' : 'Za','咋' : 'Za','拶' : 'Za','咂' : 'Za',
'栽' : 'Zai','哉' : 'Zai','灾' : 'Zai','宰' : 'Zai','载' : 'Zai','再' : 'Zai','在' : 'Zai','崽' : 'Zai','甾' : 'Zai',
'咱' : 'Zan','攒' : 'Zan','暂' : 'Zan','赞' : 'Zan','瓒' : 'Zan','昝' : 'Zan','簪' : 'Zan','糌' : 'Zan','趱' : 'Zan','錾' : 'Zan',
'赃' : 'Zang','脏' : 'Zang','葬' : 'Zang','奘' : 'Zang','驵' : 'Zang','臧' : 'Zang',
'遭' : 'Zao','糟' : 'Zao','凿' : 'Zao','藻' : 'Zao','枣' : 'Zao','早' : 'Zao','澡' : 'Zao','蚤' : 'Zao','躁' : 'Zao','噪' : 'Zao','造' : 'Zao','皂' : 'Zao','灶' : 'Zao','燥' : 'Zao','唣' : 'Zao',
'责' : 'Ze','择' : 'Ze','则' : 'Ze','泽' : 'Ze','仄' : 'Ze','赜' : 'Ze','啧' : 'Ze','帻' : 'Ze','迮' : 'Ze','昃' : 'Ze','箦' : 'Ze','舴' : 'Ze',
'贼' : 'Zei',
'怎' : 'Zen','谮' : 'Zen',
'增' : 'Zeng','憎' : 'Zeng','赠' : 'Zeng','缯' : 'Zeng','甑' : 'Zeng','罾' : 'Zeng','锃' : 'Zeng',
'扎' : 'Zha','喳' : 'Zha','渣' : 'Zha','札' : 'Zha','轧' : 'Zha','铡' : 'Zha','闸' : 'Zha','眨' : 'Zha','栅' : 'Zha','榨' : 'Zha','乍' : 'Zha','炸' : 'Zha','诈' : 'Zha','柞' : 'Zha','揸' : 'Zha','吒' : 'Zha','咤' : 'Zha','哳' : 'Zha','楂' : 'Zha','砟' : 'Zha','痄' : 'Zha','蚱' : 'Zha','齄' : 'Zha',
'瞻' : 'Zhan','毡' : 'Zhan','詹' : 'Zhan','粘' : 'Zhan','沾' : 'Zhan','盏' : 'Zhan','斩' : 'Zhan','辗' : 'Zhan','崭' : 'Zhan','展' : 'Zhan','蘸' : 'Zhan','栈' : 'Zhan','占' : 'Zhan','战' : 'Zhan','站' : 'Zhan','湛' : 'Zhan','绽' : 'Zhan','谵' : 'Zhan','搌' : 'Zhan','旃' : 'Zhan',
'樟' : 'Zhang','章' : 'Zhang','彰' : 'Zhang','漳' : 'Zhang','张' : 'Zhang','掌' : 'Zhang','涨' : 'Zhang','杖' : 'Zhang','丈' : 'Zhang','帐' : 'Zhang','账' : 'Zhang','仗' : 'Zhang','胀' : 'Zhang','瘴' : 'Zhang','障' : 'Zhang','仉' : 'Zhang','鄣' : 'Zhang','幛' : 'Zhang','嶂' : 'Zhang','獐' : 'Zhang','嫜' : 'Zhang','璋' : 'Zhang','蟑' : 'Zhang',
'招' : 'Zhao','昭' : 'Zhao','找' : 'Zhao','沼' : 'Zhao','赵' : 'Zhao','照' : 'Zhao','罩' : 'Zhao','兆' : 'Zhao','肇' : 'Zhao','召' : 'Zhao','着' : 'Zhao','诏' : 'Zhao','棹' : 'Zhao','钊' : 'Zhao','笊' : 'Zhao',
'遮' : 'Zhe','折' : 'Zhe','哲' : 'Zhe','蛰' : 'Zhe','辙' : 'Zhe','者' : 'Zhe','锗' : 'Zhe','蔗' : 'Zhe','这' : 'Zhe','浙' : 'Zhe','乇' : 'Zhe','谪' : 'Zhe','摺' : 'Zhe','柘' : 'Zhe','辄' : 'Zhe','磔' : 'Zhe','鹧' : 'Zhe','褶' : 'Zhe','蜇' : 'Zhe','螫' : 'Zhe','赭' : 'Zhe',
'珍' : 'Zhen','斟' : 'Zhen','真' : 'Zhen','甄' : 'Zhen','砧' : 'Zhen','臻' : 'Zhen','贞' : 'Zhen','针' : 'Zhen','侦' : 'Zhen','枕' : 'Zhen','疹' : 'Zhen','诊' : 'Zhen','震' : 'Zhen','振' : 'Zhen','镇' : 'Zhen','阵' : 'Zhen','帧' : 'Zhen','圳' : 'Zhen','蓁' : 'Zhen','浈' : 'Zhen','缜' : 'Zhen','桢' : 'Zhen','榛' : 'Zhen','轸' : 'Zhen','赈' : 'Zhen','胗' : 'Zhen','朕' : 'Zhen','祯' : 'Zhen','畛' : 'Zhen','稹' : 'Zhen','鸩' : 'Zhen','箴' : 'Zhen',
'蒸' : 'Zheng','挣' : 'Zheng','睁' : 'Zheng','征' : 'Zheng','狰' : 'Zheng','争' : 'Zheng','怔' : 'Zheng','整' : 'Zheng','拯' : 'Zheng','正' : 'Zheng','政' : 'Zheng','症' : 'Zheng','郑' : 'Zheng','证' : 'Zheng','诤' : 'Zheng','峥' : 'Zheng','徵' : 'Zheng','钲' : 'Zheng','铮' : 'Zheng','筝' : 'Zheng',
'芝' : 'Zhi','枝' : 'Zhi','支' : 'Zhi','吱' : 'Zhi','蜘' : 'Zhi','知' : 'Zhi','肢' : 'Zhi','脂' : 'Zhi','汁' : 'Zhi','之' : 'Zhi','织' : 'Zhi','职' : 'Zhi','直' : 'Zhi','植' : 'Zhi','殖' : 'Zhi','执' : 'Zhi','值' : 'Zhi','侄' : 'Zhi','址' : 'Zhi','指' : 'Zhi','止' : 'Zhi','趾' : 'Zhi','只' : 'Zhi','旨' : 'Zhi','纸' : 'Zhi','志' : 'Zhi','挚' : 'Zhi','掷' : 'Zhi','至' : 'Zhi','致' : 'Zhi','置' : 'Zhi','帜' : 'Zhi','峙' : 'Zhi','制' : 'Zhi','智' : 'Zhi','秩' : 'Zhi','稚' : 'Zhi','质' : 'Zhi','炙' : 'Zhi','痔' : 'Zhi','滞' : 'Zhi','治' : 'Zhi','窒' : 'Zhi','卮' : 'Zhi','陟' : 'Zhi','郅' : 'Zhi','埴' : 'Zhi','芷' : 'Zhi','摭' : 'Zhi','帙' : 'Zhi','忮' : 'Zhi','彘' : 'Zhi','咫' : 'Zhi','骘' : 'Zhi','栉' : 'Zhi','枳' : 'Zhi','栀' : 'Zhi','桎' : 'Zhi','轵' : 'Zhi','轾' : 'Zhi','贽' : 'Zhi','胝' : 'Zhi','膣' : 'Zhi','祉' : 'Zhi','黹' : 'Zhi','雉' : 'Zhi','鸷' : 'Zhi','痣' : 'Zhi','蛭' : 'Zhi','絷' : 'Zhi','酯' : 'Zhi','跖' : 'Zhi','踬' : 'Zhi','踯' : 'Zhi','豸' : 'Zhi','觯' : 'Zhi',
'中' : 'Zhong','盅' : 'Zhong','忠' : 'Zhong','钟' : 'Zhong','衷' : 'Zhong','终' : 'Zhong','种' : 'Zhong','肿' : 'Zhong','仲' : 'Zhong','众' : 'Zhong','冢' : 'Zhong','锺' : 'Zhong','螽' : 'Zhong','舯' : 'Zhong','踵' : 'Zhong',
'舟' : 'Zhou','周' : 'Zhou','州' : 'Zhou','洲' : 'Zhou','诌' : 'Zhou','粥' : 'Zhou','轴' : 'Zhou','肘' : 'Zhou','帚' : 'Zhou','咒' : 'Zhou','皱' : 'Zhou','宙' : 'Zhou','昼' : 'Zhou','骤' : 'Zhou','荮' : 'Zhou','啁' : 'Zhou','妯' : 'Zhou','纣' : 'Zhou','绉' : 'Zhou','胄' : 'Zhou','碡' : 'Zhou','籀' : 'Zhou','酎' : 'Zhou',
'珠' : 'Zhu','株' : 'Zhu','蛛' : 'Zhu','朱' : 'Zhu','猪' : 'Zhu','诸' : 'Zhu','诛' : 'Zhu','逐' : 'Zhu','竹' : 'Zhu','烛' : 'Zhu','煮' : 'Zhu','拄' : 'Zhu','瞩' : 'Zhu','嘱' : 'Zhu','主' : 'Zhu','著' : 'Zhu','柱' : 'Zhu','助' : 'Zhu','蛀' : 'Zhu','贮' : 'Zhu','铸' : 'Zhu','筑' : 'Zhu','住' : 'Zhu','注' : 'Zhu','祝' : 'Zhu','驻' : 'Zhu','伫' : 'Zhu','侏' : 'Zhu','邾' : 'Zhu','苎' : 'Zhu','茱' : 'Zhu','洙' : 'Zhu','渚' : 'Zhu','潴' : 'Zhu','杼' : 'Zhu','槠' : 'Zhu','橥' : 'Zhu','炷' : 'Zhu','铢' : 'Zhu','疰' : 'Zhu','瘃' : 'Zhu','竺' : 'Zhu','箸' : 'Zhu','舳' : 'Zhu','翥' : 'Zhu','躅' : 'Zhu','麈' : 'Zhu',
'抓' : 'Zhua','爪' : 'Zhua',
'拽' : 'Zhuai',
'专' : 'Zhuan','砖' : 'Zhuan','转' : 'Zhuan','撰' : 'Zhuan','赚' : 'Zhuan','篆' : 'Zhuan','啭' : 'Zhuan','馔' : 'Zhuan','颛' : 'Zhuan',
'椎' : 'Zhui','锥' : 'Zhui','追' : 'Zhui','赘' : 'Zhui','坠' : 'Zhui','缀' : 'Zhui','萑' : 'Zhui','惴' : 'Zhui','骓' : 'Zhui','缒' : 'Zhui','隹' : 'Zhui',
'谆' : 'Zhun','准' : 'Zhun','肫' : 'Zhun','窀' : 'Zhun',
'捉' : 'Zhuo','拙' : 'Zhuo','卓' : 'Zhuo','桌' : 'Zhuo','琢' : 'Zhuo','茁' : 'Zhuo','酌' : 'Zhuo','啄' : 'Zhuo','灼' : 'Zhuo','浊' : 'Zhuo','倬' : 'Zhuo','诼' : 'Zhuo','擢' : 'Zhuo','浞' : 'Zhuo','涿' : 'Zhuo','濯' : 'Zhuo','禚' : 'Zhuo','斫' : 'Zhuo','镯' : 'Zhuo',
'兹' : 'Zi','咨' : 'Zi','资' : 'Zi','姿' : 'Zi','滋' : 'Zi','淄' : 'Zi','孜' : 'Zi','紫' : 'Zi','仔' : 'Zi','籽' : 'Zi','滓' : 'Zi','子' : 'Zi','自' : 'Zi','渍' : 'Zi','字' : 'Zi','谘' : 'Zi','呲' : 'Zi','嵫' : 'Zi','姊' : 'Zi','孳' : 'Zi','缁' : 'Zi','梓' : 'Zi','辎' : 'Zi','赀' : 'Zi','恣' : 'Zi','眦' : 'Zi','锱' : 'Zi','秭' : 'Zi','耔' : 'Zi','笫' : 'Zi','粢' : 'Zi','趑' : 'Zi','訾' : 'Zi','龇' : 'Zi','鲻' : 'Zi','髭' : 'Zi',
'鬃' : 'Zong','棕' : 'Zong','踪' : 'Zong','宗' : 'Zong','综' : 'Zong','总' : 'Zong','纵' : 'Zong','偬' : 'Zong','腙' : 'Zong','粽' : 'Zong',
'邹' : 'Zou','走' : 'Zou','奏' : 'Zou','揍' : 'Zou','诹' : 'Zou','陬' : 'Zou','鄹' : 'Zou','驺' : 'Zou','鲰' : 'Zou',
'租' : 'Zu','足' : 'Zu','族' : 'Zu','祖' : 'Zu','诅' : 'Zu','阻' : 'Zu','组' : 'Zu','俎' : 'Zu','菹' : 'Zu','镞' : 'Zu',
'钻' : 'Zuan','纂' : 'Zuan','攥' : 'Zuan','缵' : 'Zuan','躜' : 'Zuan',
'嘴' : 'Zui','醉' : 'Zui','最' : 'Zui','罪' : 'Zui','蕞' : 'Zui','觜' : 'Zui',
'尊' : 'Zun','遵' : 'Zun','撙' : 'Zun','樽' : 'Zun','鳟' : 'Zun',
'昨' : 'Zuo','左' : 'Zuo','佐' : 'Zuo','做' : 'Zuo','作' : 'Zuo','坐' : 'Zuo','座' : 'Zuo','阼' : 'Zuo','唑' : 'Zuo','怍' : 'Zuo','胙' : 'Zuo','祚' : 'Zuo','笮' : 'Zuo',
'诶' : 'Ei',
'嗲' : 'Dia',
'岑' : 'Cen','涔' : 'Cen',
'耨' : 'Nou'}

	def GetPY(self,hz):
		try:
			index = hz.encode('utf-8')
			return self.pydict[index]
		except:
			return hz;

	def PinYin(self,hzs):
		py = []
		for hz in hzs:
			py.append(self.GetPY(hz))
		return " ".join(py)

	def printhead(self):
		self.response.out.write(
			"""
			<html><head><title>在线拼音查询工具</title></head><body><p/><p/><center>
			""")

	def printtail(self):
		self.response.out.write(
			"""
			</center></body></html>
			""")

	def printbody(self):
		self.response.out.write(
			"""
			<form action="/pinyin" method="post" name=base64 id=base64>
				<div>请输入你要查询的汉字<div>
				<div><textarea name="content" rows="3" cols="60"></textarea></div>
				<div><input type="submit" value="查询"></div>
			<form>
			""")

	def get(self):
		self.printhead()
		self.printbody()
		self.printtail()

	def post(self):
		self.printhead()
		content = cgi.escape(self.request.get('content'))
		icontent = content.encode('UTF-8')
		ucontent = unicode(content)
		self.response.out.write(icontent)
		self.response.out.write("<p/><p/>")
		self.response.out.write(self.PinYin(ucontent))
		self.response.out.write("<p/><p/><p/>")
		self.printbody()
		self.printtail()

application = webapp.WSGIApplication([('/pinyin', GetPinyin)], debug=True)

def main():
	wsgiref.handlers.CGIHandler().run(application)

if __name__ == "__main__":
	main()

